const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
// Run the real browser binding in a DOM/scheduler harness with system motion disabled.
function browser({telegram=false,mode='local-demo',preference='full',protocol='file:',ready=true}={}){
 let time=0,id=0;const frames=new Map(),timers=new Map(),ids=new Map();
 class Element{constructor(){this.style={};this.attributes={};this.textContent='';this.parentElement={append(){}};}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]??null;}remove(){}animate(){return {cancel(){},finished:Promise.resolve()};}}
 const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');for(const match of html.matchAll(/id="([^"]+)"/g))ids.set(match[1],new Element());
 const arcs=Array.from({length:4},()=>{const e=new Element();e.setAttribute('r','74.8');return e;}),paths=Array.from({length:8},()=>new Element()),gauge=new Element(),card=new Element(),root=new Element();gauge.querySelectorAll=()=>arcs;
 const document={hidden:false,documentElement:root,getElementById:id=>ids.get(id),querySelector:s=>s==='.gauge'?gauge:card,querySelectorAll:s=>s==='#arc-pulse path'?paths:[],createElement:()=>new Element(),addEventListener(){}};
 const context=vm.createContext({document,location:{protocol},BounteraClient:{mode,ready},BounteraConfig:{motion:{browserPrototype:preference}},Telegram:telegram?{WebApp:{initData:'verified-context'}}:undefined,
  matchMedia:()=>({matches:true,addEventListener(){}}),performance:{now:()=>time},requestAnimationFrame(fn){frames.set(++id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id),setTimeout:(fn,ms)=>{timers.set(++id,{fn,at:time+ms});return id;},clearTimeout:id=>timers.delete(id)});
 for(const file of ['i18n.js','motion.js','motion-dom.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets',file),'utf8'),context);
 const motion=context.createFarmZoneMotion(()=>{});
 return {motion,ids,paths,arcs,root,get pending(){return frames.size+timers.size;},step(ms){const end=time+ms;while(time<end){time=Math.min(end,time+16);for(const [id,timer] of [...timers])if(timer.at<=time){timers.delete(id);timer.fn();}const callbacks=[...frames.values()];frames.clear();callbacks.forEach(fn=>fn(time));}}};
}
function state(views=8,balance=14540,events=[]){return {user:'test',balance,progress:{number:24,views,target:10,ratio:views/10,left:10-views,bonusCents:100},events};}
const reward={id:'new-ad',type:'ad',cr:10,reference:'ad-session'};
test('file prototype runs actual SVG pulse without Telegram even with reduced-motion OS preference',()=>{const b=browser();b.motion.update(state(),{immediate:true});assert.equal(b.root.getAttribute('data-motion'),'full');b.step(2200);assert(b.paths.some(p=>p.getAttribute('d')&&Number(p.getAttribute('opacity'))>0));});
test('file prototype animates confirmed counter, balance and linear progress instead of snapping',()=>{const b=browser();b.motion.update(state());b.motion.update(state(9,14550,[reward]));assert.equal(b.ids.get('balance-number').textContent,'145.40');b.step(80);const amount=Number(b.ids.get('balance-number').textContent);assert(amount>145.40&&amount<145.50);const width=Number(b.ids.get('hub-progress-fill').getAttribute('width'));assert(width>340*.8&&width<340*.9);assert.equal(b.ids.get('view-number').textContent,'9');b.step(600);assert.equal(b.ids.get('balance-number').textContent,'145.50');assert.equal(b.ids.get('view-target').textContent,' / 10');assert.equal(Number(b.ids.get('hub-progress-fill').getAttribute('width')),306);});
test('zero progress has no highlight in standalone prototype',()=>{const b=browser();b.motion.update(state(0));b.step(10000);assert.equal(b.pending,0);assert.equal(b.ids.get('hub-progress-fill').style.visibility,'hidden');assert.equal(Number(b.ids.get('hub-clip-width').getAttribute('width')),0);assert(b.paths.every(p=>!p.getAttribute('d')));});
test('static HTTP demo also enables animation without Telegram',()=>{const b=browser({protocol:'https:'});b.motion.update(state());b.step(2300);assert.equal(b.root.getAttribute('data-motion'),'full');assert(b.paths.some(p=>p.getAttribute('d')));});
test('server-hosted browser prototype animates rewards and pulse despite reduced-motion OS setting',()=>{const b=browser({mode:'server-demo',protocol:'http:'});b.motion.update(state());assert.equal(b.root.getAttribute('data-motion'),'full');b.motion.update(state(9,14550,[reward]));b.step(80);const amount=Number(b.ids.get('balance-number').textContent);assert(amount>145.40&&amount<145.50);b.step(5700);assert.equal(b.ids.get('balance-number').textContent,'145.50');assert(b.paths.some(p=>p.getAttribute('d')&&Number(p.getAttribute('opacity'))>0));});
test('server prototype keeps zero progress unlit',()=>{const b=browser({mode:'server-demo',protocol:'http:'});b.motion.update(state(0));b.step(10000);assert.equal(b.pending,0);assert(b.paths.every(p=>!p.getAttribute('d')));});
for(const options of [{telegram:true},{mode:'server',protocol:'https:'},{preference:'system'}])test('accessibility preference stays effective outside explicit standalone override '+JSON.stringify(options),()=>{const b=browser(options);b.motion.update(state());b.motion.update(state(9,14550,[reward]));assert.equal(b.root.getAttribute('data-motion'),'reduced');assert.equal(b.ids.get('balance-number').textContent,'145.50');assert.equal(b.pending,0);});
