const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const E=require('../assets/engine.js'),C=require('../assets/config.js'),UI=require('../assets/home-ui.js');
const T=Date.UTC(2026,9,1,12),helpers={t:en=>en,loc:x=>Array.isArray(x)?x[0]:x,icon:()=>'',btn:(label,a,attrs='',css='')=>`<button class="${css}" data-action="${a}" ${attrs}>${label}</button>`,cr:x=>(x/100).toFixed(2)},view=()=>{const v=E.view(E.initial(C,T),T);v.rewardMining.freeSession.reason='daily';return v;};
test('single button shows start, addition, cooldown and finishing with no Claim',()=>{const ui=UI.create(helpers),base=view();for(const [x,label] of [[{},'Start node + 0.35 CR · ad'],[{activeCount:1},'Add +0.35 CR · ad'],[{offer:{reason:'cooldown',nextAt:T+42000}},'Next boost in 00:42'],[{status:'finishing',adPending:true},'Finishing session'],[{offer:{reason:'daily'}},'Daily charge complete']]){const html=ui.render({...base,rewardMining:{...base.rewardMining,...x}}),card=html.slice(html.indexOf('<section class="session-panel'),html.indexOf('</section>',html.indexOf('<section class="session-panel'))+10);assert(card.includes(label));assert.equal((card.match(/<button /g)||[]).length,3);assert(!card.includes('homeRewardClaim'));assert(card.includes('Until completion'));assert(card.includes('Session reward'));}});
test('Mined counter and session reward show different values using the existing components',()=>{const v=view(),ui=UI.create(helpers);Object.assign(v.rewardMining,{accumulatedMicroCents:17500000,sessionRewardCents:55,status:'active',activeCount:1});const html=ui.render(v);assert(html.includes('Mined'));assert(html.includes('0.1750'));assert(html.includes('0.55 CR'));assert(html.includes('Bonuses'));assert(!html.includes('reference-daily-charge'));assert(html.includes('role="progressbar"'));assert(html.includes('Session elapsed time'));});
test('pending requests and stale gestures cannot start or modify another session',async()=>{let v=view(),calls=0,resolve;const ui=UI.create({...helpers,view:()=>v,render(){},busy:()=>false,watchRewardAd:()=>{calls++;return new Promise(r=>resolve=r);}});const intent=ui.actionKey(v.rewardMining),first=ui.click('homeRewardAd',intent);await ui.click('homeRewardAd',intent);assert.equal(calls,1);resolve();await first;v.rewardMining.sessionId='next-session';await ui.click('homeRewardAd',intent);await ui.click('homeRewardClaim');assert.equal(calls,1);});
test('pointer held over a replaced button cannot accept its new reward',()=>{const handlers={},ctx={document:{addEventListener:(k,f)=>handlers[k]=f}};ctx.ContractsUI=require('../assets/contracts-ui.js');vm.createContext(ctx);vm.runInContext(fs.readFileSync('assets/home-ui.js','utf8'),ctx);ctx.HomeUI.create(helpers);const old={dataset:{sessionIntent:'ad:35'}},next={dataset:{sessionIntent:'ad:20'}};let prevented=false,stopped=false;handlers.pointerdown({target:{closest:()=>old}});handlers.click({target:{closest:()=>next},preventDefault:()=>prevented=true,stopImmediatePropagation:()=>stopped=true});assert(prevented&&stopped);});
test('completed reward takes priority over cooldown, daily cap, pending ads and unavailable sources',()=>{const ui=UI.create({...helpers,t:(_,ru)=>ru});for(const reason of ['cooldown','daily','pending','unavailable']){const v=view();Object.assign(v.rewardMining,{readyCents:95,sessionRewardCents:95,readySessionIds:['ready-one'],status:'ready',offer:{reason,nextAt:T+60000}});const html=ui.render(v);assert(html.includes('Добыча завершена'));assert(html.includes('Получить 0,95 CR'));assert(!html.includes('Без рекламы'));assert.equal(ui.control(v.rewardMining).action,'homeRewardClaim');assert(!ui.control(v.rewardMining).disabled);}});
test('pending or failed claims retain the displayed reward and block repeat clicks',async()=>{let resolve,calls=0,ads=0;const v=view();Object.assign(v.rewardMining,{readyCents:35,readySessionIds:['ready-one'],status:'ready'});const ui=UI.create({...helpers,view:()=>v,render(){},busy:()=>false,toast(){},watchRewardAd:async()=>ads++,action:(_,p)=>{calls++;assert.equal(p.rewardCents,35);return new Promise(r=>resolve=r);}}),first=ui.click('homeRewardClaim');assert(ui.render(v).includes('Collecting…'));await ui.click('homeRewardClaim');assert.equal(calls,1);resolve(null);await first;assert(ui.render(v).includes('Collect 0.35 CR'));assert.equal(ads,0);});
