const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),http=require('node:http');
const E=require('../assets/engine.js'),C=require('../assets/config.js'),{Store}=require('../server/store.cjs'),{handler}=require('../server/index.cjs');
const T=Date.UTC(2026,9,1,12);
function mining(){let s=E.view(E.initial(C,T),T).state,o=E.apply(s,'rewardAdOffer',E.view(s,T).rewardMining.offer,T,'offer-test');s=E.apply(o.state,'rewardAdShow',{eventId:o.event.id},T,'show-test').state;return E.apply(s,'rewardAdConfirm',{eventId:o.event.id},T+3000,'confirm-test').state;}
function browser(initial,now){let time=now,locks=0;const saved=new Map([[C.storageKey,JSON.stringify(initial)]]),context={window:{MiningConfig:C,MiningEngine:E},location:{protocol:'file:'},Date:class extends Date{static now(){return time;}},performance:{now:()=>0},crypto:{randomUUID:()=>Math.random().toString()},navigator:{locks:{request:async(_,f)=>{locks++;return f();}}},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)}};vm.createContext(context);vm.runInContext(fs.readFileSync('assets/client.js','utf8'),context);return {client:context.window.MiningClient,read:()=>JSON.parse(saved.get(C.storageKey)),advance:t=>time=t,get locks(){return locks;}};}
test('file prototype persists ready rewards when reopening and never credits without collection',async()=>{const b=browser(mining(),T+900000);await b.client.init();assert.equal(b.read().balance.cr,C.initialCRCents);await b.client.refresh();await b.client.init();assert.equal(b.read().balance.cr,C.initialCRCents);assert.equal(b.read().rewardMining.sessions[0].status,'ready');assert.equal(b.read().ledger.filter(x=>x.type==='reward_session_credit').length,0);assert.equal(b.locks,1);});
test('file prototype refresh settles under the existing browser lock and keeps the receipt on disk',async()=>{const b=browser(mining(),T+4000);await b.client.init();assert.equal(b.read().balance.cr,C.initialCRCents);b.advance(T+603000);await b.client.refresh();assert.equal(b.client.state.balance.cr,C.initialCRCents);assert.equal(b.read().rewardMining.sessions[0].status,'ready');assert.equal(b.locks,1);});
test('local collection persists credit exactly once and stays claimed after reopening',async()=>{const b=browser(mining(),T+900000);await b.client.init();const out=await b.client.mutate('rewardClaim');assert.equal(out.credited,35);await b.client.mutate('rewardClaim');await b.client.init();assert.equal(b.read().balance.cr,C.initialCRCents+35);assert.equal(b.read().ledger.filter(x=>x.type==='reward_session_credit').length,1);assert.equal(b.read().rewardMining.sessions[0].creditStatus,'credited');assert.equal(b.locks,2);});
test('GET state atomically saves ready state without adding any balance credit',async()=>{const db=new Store(':memory:');let origin;const server=http.createServer((req,res)=>handler(db,{origin})(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;try{db.ensure('user',{},T);db.persist('user',mining());const login=db.login('user'),headers={Cookie:'bountera_session='+login.token};const a=await (await fetch(origin+'/api/mining/state',{headers})).json(),b=await (await fetch(origin+'/api/mining/state',{headers})).json();assert.equal(a.state.balance.cr,C.initialCRCents);assert.equal(b.state.balance.cr,a.state.balance.cr);assert.equal(db.read('user').balance.cr,a.state.balance.cr);assert.equal(db.db.prepare("SELECT count(*) n FROM mining_ledger WHERE type='reward_session_credit'").get().n,0);}finally{await new Promise(r=>server.close(r));db.close();}});
