const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../assets/engine.js'),C=require('../assets/config.js'),S=require('../assets/cr-session-system.js'),{Store}=require('../server/store.cjs');
const T=Date.UTC(2026,9,1,12),MIN=60000;
function legacy(){const s=E.initial(C,T);E.settle(s,T);delete s.rewardMining;S.apply(s,'sessionStart',{},T,'old-session',()=>{});const x=s.crSessions.sessions[0];Object.assign(x,{durationMs:50*MIN,endsAt:T+50*MIN,baseCents:100,bonusOfferCents:25,bonusCents:25,bonusOperation:'old-bonus'});for(const k of ['maxBoosts','boostReductionMs','boostOperations'])delete x[k];s.crSessions.version=1;return s;}
test('migration retains balances, history, old promised total and deadline without duplicating records',()=>{const s=legacy(),balances=JSON.stringify(s.balance),ledger=JSON.stringify(s.ledger),old=JSON.stringify(s.crSessions.sessions[0]);E.settle(s,T);E.settle(s,T+MIN);assert.equal(JSON.stringify(s.balance),balances);assert.equal(JSON.stringify(s.ledger),ledger);assert.equal(JSON.stringify(s.crSessions.sessions[0]),old);assert.equal(s.rewardMining.version,5);assert.equal(s.rewardMining.rewards.length,1);assert.equal(s.rewardMining.rewards[0].rewardCents,125);assert.equal(s.rewardMining.rewards[0].endsAt,T+50*MIN);assert.equal(E.view(E.load(s),T+50*MIN).rewardMining.readyCents,125);});
test('retired session starts cannot create a free reward through an old action route',()=>{assert.throws(()=>E.apply(E.initial(C,T),'sessionStart',{},T),/retired/);});
test('collecting migrated sessions is atomic across the old and new claim routes',()=>{for(const order of ['new','old']){let s=legacy(),id=s.crSessions.sessions[0].id;if(order==='new'){s=E.apply(s,'rewardClaim',{},T+50*MIN,'new-claim').state;s=E.apply(s,'sessionClaim',{sessionId:id},T+50*MIN,'old-claim').state;}else{s=E.apply(s,'sessionClaim',{sessionId:id},T+50*MIN,'old-claim').state;s=E.apply(s,'rewardClaim',{},T+50*MIN,'new-claim').state;}assert.equal(s.balance.cr,C.initialCRCents+125);assert.equal(E.view(s,T+50*MIN).rewardMining.readyCents,0);assert.equal(s.ledger.filter(x=>x.cr===125).length,1);}});
test('a legacy ad already open at migration can confirm its original promised bonus before collection',()=>{let s=legacy();s.crSessions.sessions[0].bonusCents=0;s.crSessions.sessions[0].bonusOperation=null;const id=s.crSessions.sessions[0].id;s.adSessions.old={id:'old',at:T+49*MIN,readyAt:T+49*MIN+3000,expiresAt:T+54*MIN,status:'started',target:{purpose:'sessionBonus',sessionId:id}};assert.equal(E.view(s,T+50*MIN).rewardMining.readyCents,0);s=E.apply(s,'adConfirm',{id:'old'},T+50*MIN,'legacy-confirm').state;assert.equal(s.balance.cr,C.initialCRCents);assert.equal(E.view(s,T+50*MIN).rewardMining.readyCents,125);s=E.apply(s,'rewardClaim',{},T+50*MIN,'legacy-claim').state;assert.equal(s.balance.cr,C.initialCRCents+125);assert.equal(s.crSessions.sessions[0].endsAt,T+50*MIN);});
test('SQLite persists migration and claims once after reconnecting',()=>{const db=new Store(':memory:');try{db.ensure('legacy',{},T);const s=legacy();s.user.id='legacy';db.persist('legacy',s);db.act('legacy','rewardClaim',{},'legacy-claim-0001',T+50*MIN);const repeat=db.act('legacy','rewardClaim',{},'legacy-claim-0002',T+50*MIN);assert.equal(repeat.credited,0);assert.equal(db.read('legacy').balance.cr,C.initialCRCents+125);assert.equal(db.read('legacy').rewardMining.rewards.length,1);}finally{db.close();}});
