const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{Worker}=require('node:worker_threads');
const E=require('../assets/engine.js'),F=require('../assets/farm-engine.js'),C=require('../assets/app-config.js'),{Store}=require('../server/store.cjs');
const T=Date.UTC(2026,8,19,12),D=14400000;
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'farm-test-')),file=path.join(dir,'db.sqlite');let store=new Store(file);store.ensureUser('u',{},false,T);t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});return {file,get store(){return store;},reopen(){store.close();store=new Store(file);},start(now=T,key='farm-start-1'){return store.act('u','farmStart',{},key,now).session;},claim(s,now=T+D,key='farm-claim-1'){return store.act('u','farmClaim',{id:s.id},key,now);}};}
test('Farm starts with fixed 4-hour/20-cent terms and no balance credit',t=>{const f=fixture(t),s=f.start();assert.equal(s.durationMs,D);assert.equal(s.rewardCents,20);assert.equal(s.endsAt,T+D);assert.equal(s.userId,'u');assert.equal(f.store.read('u').balance.cr,0);assert.equal(F.view(f.store.read('u'),T).stats.completedSessions,0);});
test('repeated starts return the open session including an unclaimed finished session',t=>{const f=fixture(t),s=f.start();assert.equal(f.start(T+1,'second-start').id,s.id);assert.equal(f.start(T+D+999,'third-start').id,s.id);assert.equal(f.store.read('u').farm.sessions.length,1);assert.equal(f.store.read('u').farm.nextNumber,2);});
test('progress is clamped, exact in 1/10000 units, and never rounds to full reward early',t=>{const f=fixture(t),s=f.start();assert.equal(F.progress(s,T-1000).accruedUnits,0);assert.equal(F.progress(s,T+6000000).accruedUnits,833);assert.equal(F.progress(s,T+D-1).accruedUnits,1999);assert.equal(F.progress(s,T+D).accruedUnits,2000);assert.equal(F.progress(s,T+D*100).ratio,1);assert.equal(F.progress(s,T+D*100).remainingMs,0);});
test('closing/reopening database restores active progress and unclaimed rewards never expire',t=>{const f=fixture(t),s=f.start();f.reopen();assert.equal(F.view(f.store.read('u'),T+D/2).progress.accruedUnits,1000);assert.equal(F.view(f.store.read('u'),T+365*86400000).status,'ready');assert.equal(F.view(f.store.read('u'),T+D).stats.completedSessions,0);assert.equal(f.claim(s,T+365*86400000).state.balance.cr,20);});
test('early claim and spoofed payload amounts/times/user do not credit',t=>{const f=fixture(t),s=f.store.act('u','farmStart',{userId:'victim',rewardCents:999999,durationMs:1,startedAt:0},'spoof-start',T).session;assert.equal(s.rewardCents,20);assert.equal(s.startedAt,T);assert.throws(()=>f.store.act('u','farmClaim',{id:s.id,now:T+D,rewardCents:99999},'early-claim',T+D-1),/not ready/);assert.equal(f.store.read('u').balance.cr,0);});
test('other account cannot claim a session',t=>{const f=fixture(t),s=f.start();f.store.ensureUser('v',{},false,T);assert.throws(()=>f.store.act('v','farmClaim',{id:s.id,userId:'u'},'stolen-claim',T+D),/not found/);assert.equal(f.store.read('v').balance.cr,0);});
test('claim atomically creates history, links session and updates statistics once',t=>{const f=fixture(t),s=f.start(),paid=f.claim(s);assert.equal(paid.state.balance.cr,20);const tx=paid.state.ledger.find(x=>x.type==='farm');assert.equal(tx.cr,20);assert.equal(tx.reference,s.id);assert.equal(paid.claimed.ledgerId,tx.id);assert.equal(paid.claimed.claimedAt,T+D);assert.deepEqual(F.view(paid.state,T+D).stats,{completedSessions:1,totalClaimedCents:20});assert.equal(F.view(paid.state,T+D).status,'idle');assert.equal(paid.state.series.views,0);assert.equal(paid.state.farm.sessions.length,1);});
test('lost claim response and different request keys return same award without duplicates',t=>{const f=fixture(t),s=f.start(),paid=f.claim(s);f.reopen();assert.deepEqual(f.claim(s,T+D+1).claimed,paid.claimed);assert.equal(f.claim(s,T+D+2,'claim-retry-new-key').alreadyApplied,true);assert.equal(f.store.read('u').balance.cr,20);assert.equal(f.store.read('u').ledger.length,1);});
test('new settings affect only manually started next sessions',t=>{const f=fixture(t),s=f.start();f.store.config.farm={durationMs:1000,rewardCents:50};assert.equal(F.view(f.store.read('u'),T+1000).status,'farming');assert.equal(f.claim(s).state.balance.cr,20);assert.equal(f.store.read('u').farm.sessions.length,1);const next=f.start(T+D+1,'next-session');assert.equal(next.durationMs,1000);assert.equal(next.rewardCents,50);assert.equal(next.number,2);const paid=f.claim(next,next.endsAt,'next-claim');assert.deepEqual(F.view(paid.state,next.endsAt).stats,{completedSessions:2,totalClaimedCents:70});});
test('unique ledger failure rolls back balance and claim marker together',t=>{const f=fixture(t),s=f.start();f.store.db.prepare('INSERT INTO ledger VALUES(?,?,?,?,?,?,?,?,?)').run('u','conflict','farm',20,s.id,null,null,'completed','{}');assert.throws(()=>f.claim(s),/UNIQUE/);assert.equal(f.store.read('u').balance.cr,0);assert.equal(f.store.read('u').farm.sessions[0].claimedAt,null);});
test('database enforces only one unclaimed Farm session',t=>{const f=fixture(t),s=f.start();assert.throws(()=>f.store.transaction(()=>{const state=f.store.read('u');state.farm.sessions.push({...s,id:'second-session'});f.store.persist('u',state);}),/UNIQUE/);assert.equal(f.store.read('u').farm.sessions.length,1);});
async function parallel(f,action,payload,now){const source=`const {parentPort,workerData:w}=require('node:worker_threads');const {Store}=require(w.module);const s=new Store(w.file);parentPort.postMessage('ready');parentPort.once('message',()=>{try{const r=s.act('u',w.action,w.payload,w.key,w.now);parentPort.postMessage({session:r.session,claimed:r.claimed,balance:r.state.balance.cr});}catch(e){parentPort.postMessage({error:e.message});}finally{s.close();}});`;const workers=Array.from({length:4},(_,i)=>new Worker(source,{eval:true,workerData:{module:require.resolve('../server/store.cjs'),file:f.file,action,payload,now,key:action+'-parallel-'+i}}));try{await Promise.all(workers.map(w=>new Promise((resolve,reject)=>{w.once('message',resolve);w.once('error',reject);})));const results=workers.map(w=>new Promise((resolve,reject)=>{w.once('message',resolve);w.once('error',reject);}));workers.forEach(w=>w.postMessage('go'));return await Promise.all(results);}finally{await Promise.all(workers.map(w=>w.terminate()));}}
test('four concurrent starts and claims across SQLite connections create one session and one payment',async t=>{const f=fixture(t),starts=await parallel(f,'farmStart',{},T);for(const out of starts)assert.equal(out.error,undefined);assert.equal(new Set(starts.map(x=>x.session.id)).size,1);const s=starts[0].session,claims=await parallel(f,'farmClaim',{id:s.id},T+D);for(const out of claims){assert.equal(out.error,undefined);assert.equal(out.balance,20);}assert.equal(f.store.read('u').ledger.length,1);assert.equal(F.view(f.store.read('u'),T+D).stats.completedSessions,1);});
test('existing accounts migrate additively without changing balance, energy or history',()=>{const old=E.initial(C,T);delete old.farm;delete old.settings.farm;const migrated=E.migrate(old,C,T);assert.equal(migrated.balance.cr,old.balance.cr);assert.equal(migrated.energy,old.energy);assert.deepEqual(migrated.ledger,old.ledger);assert.deepEqual(migrated.farm,{sessions:[],nextNumber:1});});
