const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const F=require('../assets/farm-engine.js'),E=require('../assets/engine.js'),C=require('../assets/app-config.js');
const T=1000000;
function fixture({mode='server-demo',reduced=false}={}){
 let now=T,monotonic=0,wall=T,state=E.initial(C,T),failRead=false,loseClaim=false,failAction=false,reads=0,actions=0;
 state.settings.farm={durationMs:10000,rewardCents:20};state.balance.cr=100;
 const els=new Map(),frames=new Map(),timers=new Map(),events={};let serial=0;
 const element=id=>{if(!els.has(id))els.set(id,{textContent:'',style:{},dataset:{},attributes:{},setAttribute(k,v){this.attributes[k]=v;},removeAttribute(k){delete this.attributes[k];}});return els.get(id);};
 const document={hidden:false,getElementById:element,addEventListener:(n,f)=>events[n]=f};
 const result=()=>({state:structuredClone(state),farm:F.view(structuredClone(state),now),serverTime:now});
 const client={ready:true,mode,isDemo:true,async farmState(){reads++;if(failRead)throw Error('Network unavailable');return result();},async farmAction(action,payload){actions++;if(failAction)throw Error('Network unavailable');state=E.apply(state,action,payload,now).state;if(loseClaim&&action==='farmClaim')throw Error('Response lost');return result();}};
 const context=vm.createContext({FarmEngine:F,document,performance:{now:()=>monotonic},Date:{now:()=>wall},matchMedia:()=>({matches:reduced}),requestAnimationFrame:f=>{frames.set(++serial,f);return serial;},cancelAnimationFrame:id=>frames.delete(id),setTimeout:(f,ms)=>{timers.set(++serial,{f,at:monotonic+ms});return serial;},clearTimeout:id=>timers.delete(id)});
 vm.runInContext(fs.readFileSync(require.resolve('../assets/farm-ui.js'),'utf8'),context);
 const screen=context.createFarmScreen({client,onState(){}});
 async function flush(){await Promise.resolve();await Promise.resolve();await Promise.resolve();}
 return {screen,client,element,result,document,get state(){return state;},get reads(){return reads;},get actions(){return actions;},async enter(){screen.enter();await flush();},async advance(ms,{server=true}={}){monotonic+=ms;if(server)now+=ms;for(const [id,f]of [...frames]){frames.delete(id);f(monotonic);}for(const [id,t]of [...timers])if(t.at<=monotonic){timers.delete(id);t.f();}await flush();},warp(){wall+=10**12;},networkDown(){failRead=failAction=true;},restore(){failRead=failAction=false;},loseResponse(){loseClaim=true;},async visibility(hidden){document.hidden=hidden;events.visibilitychange();await flush();},flush};
}
test('Farm loading and offline preview never expose a false Start or zero balance',async()=>{const f=fixture();f.client.ready=false;await f.enter();assert.equal(f.element('farm-button').disabled,true);assert.equal(f.element('balance-number').textContent,'—');assert.equal(f.element('farm-accrued').textContent,'—');f.screen.connectionError('Sign in required');assert.equal(f.element('farm-error').textContent,'Sign in required');const local=fixture({mode:'local-demo'});await local.enter();await local.screen.action();assert.equal(local.actions,0);assert.equal(local.element('farm-status-text').textContent,'Server required');});
test('Farm uses monotonic time, pauses hidden frames, and restores actual progress immediately',async()=>{const f=fixture();await f.enter();await f.screen.action();await f.advance(4000);assert.equal(f.element('farm-accrued').textContent,'0.0800');const reads=f.reads;f.warp();await f.advance(1000);assert.equal(f.element('farm-accrued').textContent,'0.1000');assert.equal(f.reads,reads);await f.visibility(true);await f.advance(2000);assert.equal(f.element('farm-accrued').textContent,'0.1000');await f.visibility(false);assert.equal(f.element('farm-accrued').textContent,'0.1400');f.screen.leave();await f.advance(1000);await f.enter();assert.equal(f.element('farm-accrued').textContent,'0.1600');});
test('local timer completion waits for server readiness and cannot enable early claim',async()=>{const f=fixture();await f.enter();await f.screen.action();await f.advance(10000,{server:false});assert.equal(f.element('farm-button').disabled,true);assert.equal(f.element('farm-status-text').textContent,'Farming');assert.equal(f.state.balance.cr,100);await f.advance(10000);assert.equal(f.element('farm-button-text').textContent,'Claim 0.20 CR');assert.equal(f.element('farm-button').disabled,false);});
test('unconfirmed requests keep balance and session; retry restores server state',async()=>{const f=fixture();await f.enter();await f.screen.action();await f.advance(10000);f.networkDown();await f.screen.action();assert.equal(f.element('balance-number').textContent,'1.00');assert.equal(f.state.farm.sessions[0].claimedAt,null);assert.equal(f.element('farm-error-box').hidden,false);f.restore();await f.screen.refresh();assert.equal(f.element('farm-status-text').textContent,'Ready to claim');});
test('lost claim response reconciles with server, animates only confirmed balance and requires manual restart',async()=>{const f=fixture();await f.enter();await f.screen.action();await f.advance(10000);f.loseResponse();await f.screen.action();assert.equal(f.element('farm-button-text').textContent,'Claiming…');assert.equal(f.element('balance-number').textContent,'1.00');assert.equal(f.state.balance.cr,120);await f.screen.action();assert.equal(f.actions,2);await f.advance(700);assert.equal(f.element('balance-number').textContent,'1.20');assert.equal(f.element('farm-button-text').textContent,'Start farming');assert.equal(f.element('farm-completed').textContent,1);assert.equal(f.state.farm.sessions.length,1);assert.match(f.element('farm-hint').textContent,/\+0.20/);await f.advance(1801);assert.doesNotMatch(f.element('farm-hint').textContent,/credited/);});
test('reduced motion applies confirmed Farm balance immediately',async()=>{const f=fixture({reduced:true});await f.enter();await f.screen.action();await f.advance(10000);await f.screen.action();assert.equal(f.element('balance-number').textContent,'1.20');assert.equal(f.element('farm-total').textContent,'0.20 CR');});
