const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../assets/engine.js'),C=require('../assets/config.js'),T=Date.UTC(2026,9,2,12);
function fixture(){let now=T,writes=0,html='';const line={dataset:{},classList:{toggle(){}},get innerHTML(){return html;},set innerHTML(value){html=value;writes++;}},ctx={Date:{now:()=>now},document:{addEventListener(){},querySelector:()=>null,querySelectorAll:sel=>sel==='[data-session-live="status"]'?[line]:[]}};ctx.ContractsUI=require('../assets/contracts-ui.js');vm.createContext(ctx);vm.runInContext(fs.readFileSync('assets/home-ui.js','utf8'),ctx);const v=E.view(E.initial(C,T),T),h={icon:()=>'',t:en=>en,loc:x=>Array.isArray(x)?x[0]:x,btn:(label,a)=>`<button data-action="${a}">${label}</button>`,render:()=>render()},ui=ctx.HomeUI.create(h);
 function render(){const full=ui.render(v);line.innerHTML=full.match(/data-session-live="status">([\s\S]*?)<\/p>/)[1];line.dataset.speedEffect=full.match(/data-speed-effect="([^"]*)"/)[1];return html;}
 function active(rate,reward=20){Object.assign(v.rewardMining,{status:'active',activeCount:1,sessionId:'session-one',sessionRewardCents:reward,rate:{numerator:String(Math.round(rate*v.rewardMining.unit*100)),denominator:'1'}});}
 function boost(rate,reward=40,eventId='boost-one'){const before=JSON.parse(JSON.stringify(v.rewardMining));active(rate,reward);ui.confirmedBoost(before,v.rewardMining,{eventId});return render();}
 return {ui,v,line,render,active,boost,advance:ms=>now+=ms,get writes(){return writes},get html(){return html},text:()=>html.replace(/<[^>]*>/g,'')};
}
test('restored active session uses three decimals and a separate turquoise dot without false feedback',()=>{const f=fixture();f.active(.02049);f.render();assert.equal(f.text(),'● Mining · 0.020 CR/min');assert(f.html.includes('class="mining-speed-dot"'));f.active(.02051);f.render();assert.equal(f.text(),'● Mining · 0.021 CR/min');assert(!f.html.includes('mining-speed-transition'));});
test('confirmed boost keeps real old and new values and does not restart its animation on 150ms ticks',()=>{const f=fixture();f.active(.020);f.render();f.boost(.072);assert(f.html.includes('mining-speed-old">0.020 → '));assert(f.html.includes('mining-speed-value">0.072 CR/min'));const writes=f.writes;for(const at of [149,1,200,2300,199]){f.advance(at);f.ui.tick(f.v);assert.equal(f.writes,writes);}assert(f.html.includes('mining-speed-transition'));f.advance(1);f.ui.tick(f.v);assert.equal(f.text(),'● Mining · 0.072 CR/min');});
test('a full render resumes elapsed feedback rather than extending its 2850ms deadline',()=>{const f=fixture();f.active(.020);f.render();f.boost(.072);f.advance(2650);f.render();assert(f.html.includes('--speed-delay:-2650ms'));f.advance(200);f.render();assert.equal(f.text(),'● Mining · 0.072 CR/min');});
test('duplicate confirmation cannot restart feedback; a new boost shows the last actual rate',()=>{const f=fixture();f.active(.020);f.render();f.boost(.072);f.advance(2000);const before=JSON.parse(JSON.stringify(f.v.rewardMining));f.ui.confirmedBoost(before,f.v.rewardMining,{eventId:'boost-one',alreadyConfirmed:true});f.render();assert(f.html.includes('--speed-delay:-2000ms'));f.advance(850);f.render();assert.equal(f.text(),'● Mining · 0.072 CR/min');f.boost(.091,60,'boost-two');assert(f.html.includes('mining-speed-old">0.072 → '));assert(f.html.includes('mining-speed-value">0.091 CR/min'));});
test('free start, initial ad start, failed ads and completion never trigger boost feedback',()=>{for(const result of [{eventId:'initial-ad'},{alreadyConfirmed:true,eventId:'duplicate'},{}]){const f=fixture(),idle=JSON.parse(JSON.stringify(f.v.rewardMining));f.active(.035,35);f.ui.confirmedBoost(idle,f.v.rewardMining,result);f.render();assert.equal(f.text(),'● Mining · 0.035 CR/min');f.v.rewardMining.adPending=true;f.render();assert(!f.html.includes('mining-speed-transition'));f.v.rewardMining.status='finishing';f.render();assert.equal(f.text(),'Finishing session');f.v.rewardMining.status='ready';f.render();assert.equal(f.text(),'Mining complete');}});
test('confirmed boost immediately updates the engine rate while preserving mined amount and end time',()=>{let s=E.initial(C,T),n=0;const act=(a,p,t)=>{const out=E.apply(s,a,p,t,'speed-'+(++n));s=out.state;return out;};act('rewardFreeStart',E.view(s,T).rewardMining.freeSession,T);const offered=act('rewardAdOffer',E.view(s,T+60000).rewardMining.offer,T+60000);act('rewardAdShow',{eventId:offered.event.id},T+60000);const before=E.view(s,T+63000).rewardMining;act('rewardAdConfirm',{eventId:offered.event.id},T+63000);const after=E.view(s,T+63000).rewardMining;assert.equal(after.accumulatedMicroCents,before.accumulatedMicroCents);assert.equal(after.remainingMs,before.remainingMs);assert(Number(after.rate.numerator)/Number(after.rate.denominator)>Number(before.rate.numerator)/Number(before.rate.denominator));assert.equal(s.balance.cr,C.initialCRCents);});
