const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../assets/engine.js'),C=require('../assets/config.js'),R=require('../assets/reward-mining-system.js'),K=require('../assets/contracts-ui.js'),H=require('../assets/home-ui.js'),N=require('../assets/node-ui.js'),{Store}=require('../server/store.cjs');
const T=Date.UTC(2026,9,3,12),DAY=86400000;let seq=0;
const fresh=(c=C)=>E.view(E.initial(c,T),T).state,act=(s,a,p={},t=T)=>E.apply(s,a,p,t,`${a}-contract-test-${++seq}`),current=s=>s.rewardMining.sessions.find(x=>x.id===s.rewardMining.currentId),snap=(s,t=T)=>E.view(s,t).rewardMining;
function show(s,t){const q=snap(s,t).offer,o=act(s,'rewardAdOffer',q,t);assert(o.event);return act(o.state,'rewardAdShow',{eventId:o.event.id},t);}
function watch(s,t){const o=show(s,t);return act(o.state,'rewardAdConfirm',{eventId:o.event.id},t+3000);}
function watches(s,n,t=T){for(let i=0;i<n;i++){const at=t+i*63000;if(snap(s,at).readyCents)s=act(s,'rewardClaim',{},at).state;s=watch(s,at).state;}return s;}
const balance=s=>s.balance.cr+(s.balance.crRemainderMicroCents||0)/R.defaults.unit;
test('third confirmed view completes first contract atomically, starts the next at zero and freezes the end',()=>{
 let s=watches(fresh(),2),end=current(s).endsAt;assert.equal(snap(s,T+66000).contracts.active.progress,2);const o=show(s,T+126000),mined=snap(o.state,T+129000).accumulatedMicroCents,out=act(o.state,'rewardAdConfirm',{eventId:o.event.id},T+129000);s=out.state;
 assert.equal(out.contractCompleted.rewardCents,5);assert.equal(current(s).rewardCents,80);assert.equal(current(s).adRewardCents,75);assert.equal(current(s).contractBonusCents,5);assert.equal(current(s).endsAt,end);assert.equal(snap(s,T+129000).accumulatedMicroCents,mined);assert.equal(snap(s,T+129000).contracts.active.progress,0);assert.equal(snap(s,T+129000).contracts.active.views,5);assert.equal(s.rewardMining.contracts.completed,1);assert.equal(balance(s),C.initialCRCents);
 s=act(s,'rewardAdConfirm',{eventId:o.event.id},T+129001).state;assert.equal(current(s).rewardCents,80);assert.equal(s.rewardMining.contracts.completed,1);assert.equal(snap(s,T+129001).contracts.active.progress,0);
 s=act(s,'rewardClaim',{},end).state;assert.equal(balance(s),C.initialCRCents+80);assert.deepEqual(s.ledger.find(x=>x.type==='reward_session_credit').breakdown,{viewsCents:75,contractsCents:5,sponsorsCents:0,freeCents:0,totalCents:80});
});
test('second contract needs five new views and both bonuses are counted once per day',()=>{
 let s=watches(fresh(),7);assert.equal(s.rewardMining.contracts.completed,1);assert.equal(snap(s,T+381000).contracts.active.progress,4);s=watch(s,T+441000).state;assert.equal(s.rewardMining.contracts.completed,2);assert(snap(s,T+444000).contracts.allComplete);assert.equal(current(s).contractBonusCents,15);s=watch(s,T+504000).state;assert.equal(s.rewardMining.contracts.completed,2);assert.equal(current(s).contractBonusCents,15);assert.equal(s.rewardMining.contracts.days[snap(s,T).contracts.key].committedCents,15);
});
test('free launch and failed ad outcomes do not advance contract progress',()=>{
 const s=act(fresh(),'rewardFreeStart',snap(fresh()).freeSession).state;assert.equal(snap(s).contracts.active.progress,0);for(const outcome of ['cancelled','error','no-offer']){const o=show(s,T),out=act(o.state,'rewardAdFinish',{eventId:o.event.id,outcome},T+3000);assert.equal(snap(out.state,T+3000).contracts.active.progress,0);assert.equal(current(out.state).rewardCents,5);}assert.equal(watch(s,T).state.rewardMining.contracts.days[snap(s).contracts.key].items[0].progress,1);
});
test('contract progress spans mining sessions and restores through JSON persistence',()=>{
 let s=watches(fresh(),2);s=act(s,'rewardClaim',{},T+603000).state;s=watch(E.load(s),T+604000).state;assert.equal(s.rewardMining.contracts.completed,1);assert.equal(current(s).rewardCents,25);assert.equal(current(s).contractBonusCents,5);assert.equal(snap(E.load(s),T+607000).contracts.active.progress,0);
});
test('Moscow midnight expires incomplete contracts while preserving earned rewards and permanent achievements',()=>{
 const boundary=Date.UTC(2026,9,3,21),at=boundary-130000;let s=watches(fresh(),3,at);const before=current(s).rewardCents,key=snap(s,boundary-1000).contracts.key;s=act(E.load(s),'refresh',{},boundary).state;const v=snap(s,boundary);assert.equal(v.contracts.key,key+1);assert.equal(v.contracts.active.progress,0);assert.equal(v.contracts.completedTotal,1);assert.equal(current(s).rewardCents,before);assert.equal(s.rewardMining.contracts.days[key].items[1].status,'expired');assert.equal(s.balance.cr,C.initialCRCents);
});
test('view started before midnight retains its day but late confirmation cannot revive an expired contract',()=>{
 const boundary=Date.UTC(2026,9,3,21);let s=watches(fresh(),2,boundary-127000),o=show(s,boundary-1000),key=o.event.contractDay;s=act(o.state,'rewardAdConfirm',{eventId:o.event.id},boundary+2000).state;assert.equal(s.rewardMining.events[o.event.id].contractDay,key);assert.equal(s.rewardMining.contracts.completed,0);assert.equal(snap(s,boundary+2000).contracts.active.progress,0);assert.equal(current(s).rewardCents,75);assert.equal(s.rewardMining.contracts.days[key].items[0].status,'expired');
});
test('contract bonus enters a finishing session after confirmation and is not multiplied by Tier',()=>{
 let s=watches(fresh(),2),o=show(s,T+602000);s=act(o.state,'refresh',{},T+603000).state;assert.equal(snap(s,T+603000).status,'finishing');s=act(s,'rewardAdConfirm',{eventId:o.event.id},T+605000).state;assert.equal(snap(s,T+605000).readyCents,80);assert.equal(balance(s),C.initialCRCents);assert.equal(s.rewardMining.contracts.completed,1);
});
test('timeout then late confirming third view creates an exact ready correction and pays contract funding once',()=>{
 let s=watches(fresh(),2),o=show(s,T+602000),late=T+902000;s=act(o.state,'rewardClaim',{},late).state;assert.equal(balance(s),C.initialCRCents+55);s=act(s,'rewardAdConfirm',{eventId:o.event.id},late+1).state;assert.equal(snap(s,late+1).readyCents,25);assert.equal(s.rewardMining.contracts.completed,1);s=act(s,'rewardClaim',{},late+2).state;s=act(s,'rewardAdConfirm',{eventId:o.event.id},late+3).state;s=act(s,'rewardClaim',{},late+4).state;assert.equal(balance(s),C.initialCRCents+80);assert.equal(s.rewardMining.contracts.days[snap(s,late+4).contracts.key].paidCents,5);assert.equal(s.ledger.filter(x=>x.type==='reward_session_adjustment').length,1);
});
test('unfunded contracts are not promised; ordinary reward sessions still work',()=>{
 let s=fresh({...C,rewardMining:{contracts:{dailyBudgetCents:0}}});assert.equal(snap(s).contracts.active,null);s=watches(s,3);assert.equal(current(s).rewardCents,75);assert.equal(s.rewardMining.contracts.completed,0);assert.equal(snap(s,T+129000).contracts.active,null);
 s=fresh();const k=snap(s).contracts.key;s.rewardMining.settings.contracts.dailyBudgetCents=0;s=watches(s,3);assert.equal(s.rewardMining.contracts.days[k].allocatedCents,15);assert.equal(s.rewardMining.contracts.completed,1);assert.equal(snap(s,T+DAY).contracts.active,null);
});
test('reserved boosted price and contract funding survive a later reduction of configured budgets',()=>{
 let s=watches(fresh(),2),o=show(s,T+126000);o.state.rewardMining.settings.dailyBudgetCents=0;o.state.rewardMining.settings.contracts.dailyBudgetCents=0;s=act(o.state,'rewardAdConfirm',{eventId:o.event.id},T+129000).state;assert.equal(current(s).rewardCents,80);assert.equal(s.rewardMining.contracts.completed,1);assert.equal(s.rewardMining.day.allocatedCents,2075);assert.equal(snap(s,T+DAY).contracts.active,null);s=act(s,'rewardClaim',{},T+DAY).state;assert.equal(snap(s,T+DAY).offer.reason,'unavailable');
});
test('six lifetime contracts unlock X-2800 without XP or parts; installation only follows collection',()=>{
 let s=fresh();assert.throws(()=>act(s,'rewardUnlock',{id:'reward-t2'}),/Requirements/);for(let d=0;d<3;d++){s=watches(s,8,T+d*DAY);s=act(s,'rewardClaim',{},T+d*DAY+603000).state;}assert.equal(s.rewardMining.contracts.completed,6);s.user.xp=0;s.rewardMining.parts=0;s=act(s,'rewardUnlock',{id:'reward-t2'},T+2*DAY+603000).state;assert.equal(s.rewardMining.parts,0);s=act(s,'rewardSelect',{id:'reward-t2'},T+2*DAY+603000).state;assert.equal(snap(s,T+2*DAY+603000).node.name[0],'X-2800');s=watch(s,T+2*DAY+664000).state;const end=current(s).endsAt,total=current(s).rewardCents;assert.throws(()=>act(s,'rewardSelect',{id:'reward-t1'},T+2*DAY+664001),/Collect/);assert.throws(()=>act(s,'rewardSelect',{id:'reward-t1'},end),/Collect/);s=act(s,'rewardClaim',{},end).state;s=act(s,'rewardSelect',{id:'reward-t1'},end).state;assert.equal(s.rewardMining.sessions.at(-1).rewardCents,total);
});
test('fractional Tier reward survives repeated sessions and wallet credit without cent rounding loss',()=>{
 let s=fresh({...C,rewardMining:{contracts:{enabled:false}}});s.rewardMining.contracts.completed=6;s=act(s,'rewardUnlock',{id:'reward-t2'}).state;s=act(s,'rewardSelect',{id:'reward-t2'}).state;
 assert.equal(snap(s).offer.rewardCents,36.75);assert.equal(K.amount(36.75),'0.3675');for(let i=0;i<4;i++){const at=T+i*700000;s.rewardMining.cursor=0;s=watch(s,at).state;s=act(E.load(s),'rewardClaim',{},at+603000).state;assert.equal(balance(s),C.initialCRCents+36.75*(i+1));}assert.equal(s.balance.crRemainderMicroCents,0);assert.equal(s.balance.cr,C.initialCRCents+147);assert.equal(s.rewardMining.sessions[0].adRewardCents,36.75);assert.equal(s.ledger.filter(x=>x.type==='reward_session_credit').length,4);
});
test('Tier applies only to base ad price, not contract or sponsor bonuses',()=>{
 let s=fresh();s.rewardMining.unlocked.push('reward-t2');s=act(s,'rewardSelect',{id:'reward-t2'}).state;s=watches(s,3);assert.equal(current(s).adRewardCents,78.75);assert.equal(current(s).contractBonusCents,5);assert.equal(current(s).rewardCents,83.75);
 s=fresh();s.rewardMining.selected='reward-t2';s.rewardMining.settings.sources=[{id:'sponsor',quota:25,rewardCents:20,sponsorBonusCents:10,campaignId:'test'}];s.rewardMining.settings.tiers[1].campaignIds=['test'];const q=snap(s).offer;assert.equal(q.adRewardCents,21);assert.equal(q.sponsorBonusCents,10);assert.equal(q.rewardCents,31);s=watch(s,T).state;assert.equal(current(s).adRewardCents,21);assert.equal(current(s).sponsorBonusCents,10);assert.equal(current(s).rewardCents,31);
});
test('contract events and bonuses persist transactionally and cannot affect a different player',()=>{
 const db=new Store(':memory:');try{let s=watches(fresh(),2);db.ensure('a',{},T);db.persist('a',s);db.ensure('b',{},T);const q=snap(s,T+126000).offer,o=db.act('a','rewardAdOffer',q,'contract-offer-test',T+126000);db.act('a','rewardAdShow',{eventId:o.event.id},'contract-show-test',T+126000);db.act('a','rewardAdConfirm',{eventId:o.event.id},'contract-confirm-test',T+129000);db.act('a','rewardAdConfirm',{eventId:o.event.id},'contract-confirm-test',T+129001);db.act('a','rewardAdConfirm',{eventId:o.event.id},'contract-confirm-other',T+129002);assert.equal(db.read('a').rewardMining.contracts.completed,1);assert.equal(db.read('b').rewardMining.contracts.completed,0);assert.throws(()=>db.act('b','rewardAdConfirm',{eventId:o.event.id},'contract-foreign-test',T+129000),/not found/);db.ensure('a',{},T+DAY);db.act('a','rewardClaim',{},'contract-claim-test',T+DAY);assert.equal(balance(db.read('a')),C.initialCRCents+80);assert.equal(db.read('a').rewardMining.contracts.completed,1);}finally{db.close();}
});
test('v4 migration keeps old funds, timestamps, ledger and owned models without retroactive contracts',()=>{
 let s=watches(fresh(),2);s.rewardMining.version=4;delete s.rewardMining.contracts;delete s.rewardMining.settings.contracts;for(const e of Object.values(s.rewardMining.events))delete e.contractDay;s.rewardMining.unlocked.push('reward-t2');const ledger=JSON.stringify(s.ledger),end=current(s).endsAt,ready=E.view(s,end);assert.equal(ready.state.rewardMining.version,5);assert.equal(ready.rewardMining.readyCents,55);assert.equal(ready.rewardMining.contracts.completedTotal,0);assert.equal(JSON.stringify(ready.state.ledger),ledger);assert(ready.rewardMining.unlocked.includes('reward-t2'));assert.equal(ready.state.balance.cr,C.initialCRCents);
});
const helpers={t:en=>en,loc:x=>Array.isArray(x)?x[0]:x,icon:()=>'',btn:(label,a,attrs='',css='')=>`<button class="${css}" data-action="${a}" ${attrs}>${label}</button>`,cr:K.amount,esc:String};
test('Home contract opens conditions without ads; time scale fills independently of daily views',async()=>{
 const v=E.view(watches(fresh(),2),T+126000);let ads=0,opened='',ui=H.create({...helpers,view:()=>v,watchRewardAd:async()=>ads++,openSheet:(_,html)=>opened=html});const html=ui.render(v);assert(html.includes('Mining contract 2/3'));assert(!html.includes('mining-contract-row'));assert(html.includes('aria-label="Session elapsed time"'));assert(html.includes('aria-valuenow="21"'));assert.equal((html.match(/class="mining-progress-segment"/g)||[]).length,6);await ui.click('homeContract');assert.equal(ads,0);assert(opened.includes('Europe/Moscow'));assert(opened.includes('2 of 3'));assert(opened.includes('contractTasks'));const ready=E.view(v.state,T+603000);assert(ui.render(ready).includes('scaleX(1)'));
});
test('Tasks shows sequential contracts, empty sponsors and exact read-only campaign conditions',()=>{
 const ui=K.create(helpers),x=snap(fresh());let html=ui.tasks(x);assert(html.includes('Confirm 3'));assert(html.includes('5 views · +0.10 CR'));assert(html.includes('No active campaigns right now'));assert(!html.includes('watchAd'));
 const s=fresh();s.rewardMining.settings.campaigns=[{id:'test',name:['Test','Тест'],partner:['Partner','Партнёр'],offer:['Offer','Предложение'],active:true,demo:true,rewardCents:36.75,requiredTier:2,action:['Demo action','Демо-действие'],restrictions:['Once','Один раз'],confirmation:['Demo callback','Демо-callback'],endsAt:T+DAY}];const c=snap(s).campaigns[0];assert(!c.eligible);html=ui.tasks(snap(s));assert(html.includes('Demo'));assert(html.includes('0.3675 CR'));assert(html.includes('Requires Tier 2 → Hangar'));assert(ui.campaignDetails(c).includes('Confirmation'));assert.equal(snap(s,T+DAY).campaigns.length,0);assert.equal(snap(fresh()).campaigns.length,0);
});
test('Hangar has a lifetime contract target and no XP/parts prerequisite for X-2800',()=>{
 const v=E.view(fresh(),T);v.rewardMining.contracts.completedTotal=4;const ui=N.create({...helpers,system:require('../assets/node-system.js'),duration:String}),html=ui.render(v);assert(html.includes('Next node: X-2800'));assert(html.includes('Contracts completed: 4/6'));assert(html.includes('4/6'));assert(html.includes('Example: 0.20 → 0.21 CR'));assert(!html.includes('50 XP'));assert(!html.includes('Unlock · 3 parts'));
});
