const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function setup(){let now=0,id=0;const frames=new Map(),events={},modal={open:false,style:{setProperty(k,v){this[k]=v;}}},doc={hidden:false,getElementById:()=>modal,querySelector:()=>({getBoundingClientRect:()=>({top:44,bottom:140})}),addEventListener:(n,fn)=>events[n]=fn},media={matches:false,addEventListener(){}};const c={document:doc,window:{addEventListener(){},visualViewport:{offsetTop:0,height:844,addEventListener(){}}},innerHeight:844,matchMedia:()=>media,performance:{now:()=>now},requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id)};vm.createContext(c);vm.runInContext(fs.readFileSync('assets/motion.js','utf8'),c);return {m:c.MotionUI,frames,doc,media,modal,events,step(t){now=t;const run=[...frames.values()];frames.clear();run.forEach(fn=>fn(t));}};}
test('counter interpolation stays within confirmed amount, shares one frame and stops at completion',()=>{const f=setup(),a={isConnected:true,textContent:''},b={isConnected:true,textContent:''};f.m.number(a,100,n=>n.toFixed(2));assert.equal(f.frames.size,0);f.m.number(a,200,n=>n.toFixed(2));f.m.number(b,30,n=>n.toFixed(2),{from:0});assert.equal(f.frames.size,1);f.step(70);assert(+a.textContent>100&&+a.textContent<200);assert(+b.textContent>0&&+b.textContent<30);f.step(160);assert.equal(a.textContent,'200.00');assert.equal(b.textContent,'30.00');assert.equal(f.frames.size,0);});
test('background, reduced motion and open dialogs avoid running counter animation',()=>{for(const mode of ['background','reduced','dialog']){const f=setup(),el={isConnected:true,textContent:''};f.m.number(el,0,String);if(mode==='background')f.doc.hidden=true;if(mode==='reduced')f.media.matches=true;if(mode==='dialog')f.modal.open=true;f.m.number(el,100,String);assert.equal(el.textContent,'100');assert.equal(f.frames.size,0);}const f=setup(),el={isConnected:true,textContent:''};f.m.number(el,100,String,{from:0});f.doc.hidden=true;f.events.visibilitychange();assert.equal(f.frames.size,0);assert.equal(el.textContent,'100');});
test('dialog opens at the header top edge within visual viewport, including keyboard resize',()=>{const f=setup();f.m.dialogBounds();assert.equal(f.modal.style['--dialog-top'],'44px');assert.equal(f.modal.style['--dialog-height'],'784px');f.doc.querySelector=()=>({getBoundingClientRect:()=>({top:-20,bottom:140})});f.m.dialogBounds();assert.equal(f.modal.style['--dialog-top'],'0px');});

test('claim feedback is bounded, uses confirmed DATA, preserves device transform and cleans up',async()=>{
 const f=setup(),elements=[],animations=[];let cancelCount=0;
 const node=(className='')=>({className,style:{},setAttribute(){},remove(){this.removed=true;},getBoundingClientRect:()=>({left:70,top:200,width:200,height:210}),animate(frames,options){let resolve;const finished=new Promise(r=>resolve=r);const a={frames,options,finished,finish:resolve,cancel(){cancelCount++;}};animations.push(a);return a;}});
 const device=node('device'),hero=node('hero'),balance=node('balance');
 f.doc.querySelector=s=>s==='.journey-device'?device:s==='.journey-hero'?hero:null;
 f.doc.querySelectorAll=()=>[balance];f.doc.createElement=()=>node();f.doc.body={append:e=>elements.push(e)};
 // Read the same script with a browser-style computed accent, retaining the fixture clock.
 const context={document:f.doc,window:{addEventListener(){}},innerHeight:844,getComputedStyle:()=>({getPropertyValue:()=> '#60f2ec'}),matchMedia:()=>f.media,performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){}};
 vm.createContext(context);vm.runInContext(fs.readFileSync('assets/motion.js','utf8'),context);context.MotionUI.claim(79500);
 assert.equal(elements.length,9);assert.equal(elements.filter(e=>e.className.includes('claim-particle')).length,6);assert.equal(elements.find(e=>e.className.includes('claim-data-feedback')).textContent,'+0.0795 DATA');
 assert(animations.some(a=>a.frames[0].scale==='1.03'&&!('transform' in a.frames[0])));assert(animations.every(a=>a.options.duration<=760));
 animations.forEach(a=>a.finish());await Promise.resolve();assert(elements.every(e=>e.removed));assert(!device.removed&&!balance.removed);
 context.MotionUI.claim(120000);f.doc.hidden=true;f.events.visibilitychange();assert(elements.every(e=>e.removed));assert(cancelCount>0);
 const count=elements.length;context.MotionUI.claim(100000);assert.equal(elements.length,count);f.doc.hidden=false;f.media.matches=true;context.MotionUI.claim(100000);assert.equal(elements.length,count);
});
