const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../assets/engine.js'),N=require('../assets/node-engine.js'),C=require('../assets/app-config.js');
const H=3600000,D=24*H,T=Date.UTC(2026,8,19,12);
function init(){return E.apply(E.initial(C,T),'nodeRefresh',{},T).state;}
function apply(s,a,p={},now=T){return E.apply(s,a,p,now);}
function ad(s,kind,now=T,id='demo-ad-request'){s=apply(s,'nodeAdStart',{kind,requestId:id},now).state;return apply(s,'nodeAdConfirm',{id},now+3001);}
test('Node initializes without changing balance and renders fractional monotonic time',()=>{const s=init(),v=N.view(s,T+.7);assert.equal(s.balance.cr,12540);assert.equal(v.node.levels.bandwidth,3);assert.equal(v.node.levels.storage,2);assert.equal(v.node.levels.cpu,1);assert.equal(v.node.levels.gpu,0);assert(v.ratio>.74&&v.ratio<.76);assert.equal(v.uptimeBps,9420);assert.equal(v.streak,5);});
test('buffer accrues while closed, caps, and preserves exact sub-cent remainder',()=>{const s=init(),v=N.view(s,T+H*2);assert.equal(v.ratio,1);assert.equal(v.node.bufferMicro,v.capacityMicro);const paid=apply(s,'nodeCollect',{requestId:'collection-001'},T);assert.equal(paid.state.balance.cr,s.balance.cr+paid.creditCents);assert(paid.state.node.bufferMicro<10000);assert.equal(paid.state.ledger[0].type,'node_reward');assert.equal(paid.state.node.totalClaimedCents,paid.creditCents);});
test('repeated collection cannot double-credit',()=>{const first=apply(init(),'nodeCollect',{requestId:'collection-repeat'},T);const retry=apply(first.state,'nodeCollect',{requestId:'collection-repeat'},T);assert.equal(retry.alreadyApplied,true);assert.equal(retry.state.balance.cr,first.state.balance.cr);assert.equal(retry.state.node.harvests,1);});
test('upgrade spends exact CR and does not retroactively change accrued income',()=>{const s=init(),before=s.node.bufferMicro,out=apply(s,'nodeUpgrade',{resource:'bandwidth'});assert.equal(out.state.balance.cr,s.balance.cr-1500);assert.equal(out.state.node.levels.bandwidth,4);assert.equal(out.state.node.bufferMicro,before);assert.equal(out.state.ledger[0].cr,-1500);assert(N.view(out.state,T).rateMicro>N.view(s,T).rateMicro);});
test('GPU unlocks with fifth friend, cluster scales to 25%, and max resources are enforced',()=>{let s=init();assert.throws(()=>apply(s,'nodeUpgrade',{resource:'gpu'}),/unlocks/);s=apply(s,'nodeDemo',{kind:'friend'}).state;s=apply(s,'nodeUpgrade',{resource:'gpu'}).state;assert.equal(s.node.levels.gpu,1);while(s.node.friends.length<10)s=apply(s,'nodeDemo',{kind:'friend'}).state;assert.equal(N.view(s,T).clusterBonus,25);s.node.levels.bandwidth=5;assert.throws(()=>apply(s,'nodeUpgrade',{resource:'bandwidth'}),/fully upgraded/);});
test('traffic ads enforce completion, cancellation, duplicate reward and 3h cooldown',()=>{let s=init();s=apply(s,'nodeAdStart',{kind:'traffic',requestId:'traffic-first'}).state;assert.throws(()=>apply(s,'nodeAdConfirm',{id:'traffic-first'},T+1000),/Complete/);const paid=apply(s,'nodeAdConfirm',{id:'traffic-first'},T+3001);assert.equal(paid.state.node.boostUntil,T+3001+H/2);assert.equal(paid.state.node.usage.total,1);assert.equal(apply(paid.state,'nodeAdConfirm',{id:'traffic-first'},T+4000).state.node.usage.total,1);assert.throws(()=>apply(paid.state,'nodeAdStart',{kind:'traffic',requestId:'traffic-second'},T+H),/3 hours/);s=apply(paid.state,'nodeAdStart',{kind:'buffer',requestId:'cancel-ad'},T+5000).state;s=apply(s,'nodeAdCancel',{id:'cancel-ad'},T+5100).state;assert.throws(()=>apply(s,'nodeAdConfirm',{id:'cancel-ad'},T+9000),/Complete/);});
test('traffic expiration integrates boosted and ordinary income correctly',()=>{let s=init();s.node.bufferMicro=0;s.node.lastAt=T;s.node.boostUntil=T+H/2;assert.equal(N.view(s,T).remainingMs,3.5*H);const rate=N.view(s,T+H).rateMicro,v=N.view(s,T+H);assert(Math.abs(v.node.bufferMicro-Math.floor(rate*1.5))<=1);});
test('expanded buffer doubles capacity for 24 hours without deleting existing pending income on expiry',()=>{const s=ad(init(),'buffer').state,v=N.view(s,T+3001);assert.equal(v.capacityMicro,N.view(init(),T).capacityMicro*2);const later=N.view(s,T+26*H);assert(later.node.bufferMicro>0);assert.throws(()=>ad(s,'buffer',T+10000,'buffer-again'),/expanded today/);});
test('healthy daily pings unlock x1.5, missed day loses multiplier, free collect does not bypass restoration',()=>{let s=init();s=apply(s,'nodeCollect',{requestId:'day-six-ping'},T+D).state;assert.equal(N.view(s,T+D).streak,6);s=apply(s,'nodeCollect',{requestId:'day-seven-ping'},T+2*D).state;assert.equal(N.view(s,T+2*D).multiplier,1.5);s=apply(s,'nodeRefresh',{},T+4*D).state;assert.equal(N.view(s,T+4*D).uptimeBps,6000);assert.equal(N.view(s,T+4*D).streak,0);s=apply(s,'nodeCollect',{requestId:'after-missed-ping'},T+4*D).state;assert(N.view(s,T+4*D).uptimeBps<9000);s=ad(s,'restore',T+4*D,'restore-ad').state;assert.equal(N.view(s,T+4*D+3001).uptimeBps,9000);assert.equal(N.view(s,T+4*D+3001).streak,1);});
test('instant/double rewards use real pending buffer, limits and overload bonus only once',()=>{let s=init();s=apply(s,'nodeCollect',{requestId:'initial-collect'}).state;s=apply(s,'nodeRefresh',{},T+H).state;const before=Math.floor(N.view(s,T+H+3001).node.bufferMicro/10000),r=ad(s,'instant',T+H,'instant-ad');assert.equal(r.creditCents,Math.floor(before*1.1));s=r.state;s=apply(s,'nodeDemo',{kind:'event'},T+H+5000).state;s=ad(s,'overload',T+H+5000,'event-ad').state;assert.equal(s.node.overloadBonus,true);const doubled=ad(s,'double',T+H*2,'double-ad');assert(doubled.creditCents>0);assert.equal(doubled.state.node.overloadBonus,false);assert.equal(doubled.state.node.usage.double,1);});
test('Home and Tasks update stability and certification once per verified action',()=>{let s=init();s.settings.ads.demoDurationSeconds=0;for(let i=0;i<5;i++){const a=apply(s,'startAd',{},T+i);s=apply(a.state,'confirmAd',{id:a.session.id},T+i).state;}assert.equal(N.view(s,T+5).uptimeBps,9520);for(const id of ['community','news','community-bot']){s=apply(s,'startTask',{id},T+10).state;s=apply(s,'verifyTask',{id},T+10).state;}assert.equal(s.node.certifiedUntil,T+10+D);const again=apply(s,'verifyTask',{id:'community'},T+11).state;assert.equal(again.node.tasksToday,3);});
test('Farm daily ad cap, paid restoration and demo time controls work',()=>{let s=init();s.node.usage.total=10;assert.throws(()=>ad(s,'buffer'),/Daily Farm ad limit/);s=apply(s,'nodeDemo',{kind:'advance',ms:2*D}).state;assert.equal(s.node.uptimeBps,6000);const before=s.balance.cr;s=apply(s,'nodeRestore').state;assert.equal(s.balance.cr,before-1000);assert.equal(N.view(s,T).uptimeBps,9000);s=apply(s,'nodeDemo',{kind:'demand',bps:7000}).state;assert.equal(N.view(s,T).demand,70);});
