const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../assets/engine.js'),C=require('../assets/config.js'),H=require('../assets/home-ui.js'),K=require('../assets/contracts-ui.js'),{Store}=require('../server/store.cjs');
const T=Date.UTC(2026,9,3,8),DAY=86400000;let id=0;
const act=(s,a,p={},at=T)=>E.apply(s,a,p,at,'panel-test-'+(++id));
const fresh=c=>act(E.initial(c||C,T),'refresh').state;
function watches(s,n){for(let i=0;i<n;i++){const at=T+i*65000,v=E.view(s,at);if(v.rewardMining.readyCents)s=act(s,'rewardClaim',{},at).state;const o=act(s,'rewardAdOffer',E.view(s,at).rewardMining.offer,at);s=act(o.state,'rewardAdShow',{eventId:o.event.id},at).state;s=act(s,'rewardAdConfirm',{eventId:o.event.id},at+3000).state;}return s;}
const helpers={t:en=>en,loc:x=>Array.isArray(x)?x[0]:x,icon:n=>'<svg data-icon="'+n+'"></svg>',btn:(l,a,attrs='',css='')=>`<button class="${css}" data-action="${a}" ${attrs}>${l}</button>`};
test('10/50 view bonuses are funded separately and require explicit collection exactly once',()=>{let s=watches(fresh(),50),at=T+50*65000;const v=E.view(s,at).rewardMining;assert.deepEqual(v.viewBonuses.today.map(x=>[x.views,x.rewardCents,x.status]),[[10,5,'ready'],[50,10,'ready']]);assert.equal(s.ledger.filter(x=>x.type==='reward_view_bonus').length,0);const base=s.balance.cr,key=v.day.key;let o=act(s,'rewardViewBonusClaim',{dayKey:key,views:10},at);s=o.state;assert.equal(o.credited,5);s=act(s,'rewardViewBonusClaim',{dayKey:key,views:10},at).state;assert.equal(s.balance.cr,base+5);s=act(s,'rewardViewBonusClaim',{dayKey:key,views:50},at).state;assert.equal(s.balance.cr,base+15);assert.equal(s.rewardMining.days[key].viewBonuses.paidCents,15);assert.equal(s.ledger.filter(x=>x.type==='reward_view_bonus').length,2);});
test('unearned view bonuses cannot be claimed; free launch and cancelled ads do not progress them',()=>{let s=fresh(),v=E.view(s,T);assert.throws(()=>act(s,'rewardViewBonusClaim',{dayKey:v.rewardMining.day.key,views:10}),/not ready/);s=act(s,'rewardFreeStart',v.rewardMining.freeSession).state;const o=act(s,'rewardAdOffer',E.view(s,T).rewardMining.offer);s=act(o.state,'rewardAdShow',{eventId:o.event.id}).state;s=act(s,'rewardAdFinish',{eventId:o.event.id,outcome:'cancelled'},T+3000).state;assert.equal(E.view(s,T+3000).rewardMining.viewBonuses.today[0].progress,0);});
test('earned view bonuses survive closing and midnight; unused progress resets with view quotas',()=>{let s=watches(fresh(),10),key=E.view(s,T+650000).rewardMining.day.key;s=act(E.load(s),'refresh',{},T+DAY).state;let b=E.view(s,T+DAY).rewardMining.viewBonuses;assert.equal(b.today[0].progress,0);assert.equal(b.pending.length,1);assert.equal(b.pending[0].dayKey,key);s=act(s,'rewardViewBonusClaim',{dayKey:key,views:10},T+DAY).state;assert.equal(E.view(E.load(s),T+DAY).rewardMining.viewBonuses.pending.length,0);assert.equal(s.rewardMining.days[key].viewBonuses.items[0].claimedAt,T+DAY);});
test('unfunded bonuses are not available; existing reservations survive later budget changes',()=>{let s=fresh({...C,rewardMining:{viewBonuses:{dailyBudgetCents:0}}});assert.equal(E.view(s,T).rewardMining.viewBonuses.today[0].status,'unavailable');s=watches(fresh(),10);s.rewardMining.settings.viewBonuses.dailyBudgetCents=0;const key=E.view(s,T+650000).rewardMining.day.key;s=act(s,'rewardViewBonusClaim',{dayKey:key,views:10},T+650000).state;assert.equal(s.rewardMining.days[key].viewBonuses.paidCents,5);assert.equal(E.view(s,T+DAY).rewardMining.viewBonuses.today[0].status,'unavailable');});
test('SQLite view bonus claim is transactional and replay protected across reloads',()=>{const db=new Store(':memory:');try{let s=watches(fresh(),10),key=E.view(s,T+650000).rewardMining.day.key;db.ensure('panel-a',{},T);db.persist('panel-a',s);const base=s.balance.cr;db.act('panel-a','rewardViewBonusClaim',{dayKey:key,views:10},'panel-bonus-once',T+650000);db.act('panel-a','rewardViewBonusClaim',{dayKey:key,views:10},'panel-bonus-once',T+650001);db.act('panel-a','rewardViewBonusClaim',{dayKey:key,views:10},'panel-bonus-again',T+650002);assert.equal(db.read('panel-a').balance.cr,base+5);assert.equal(db.read('panel-a').ledger.filter(x=>x.type==='reward_view_bonus').length,1);}finally{db.close();}});
test('compact header removes external rows; gift and ring only open conditions without claiming or ads',async()=>{const s=watches(fresh(),1),v=E.view(s,T+3000);let calls=0,ads=0,opened='';const ui=H.create({...helpers,view:()=>v,action:async()=>calls++,watchRewardAd:async()=>ads++,openSheet:(_,html)=>opened=html});const html=ui.render(v);assert(html.includes('Mining contract 1/3'));assert(html.includes('stroke-dasharray="33.33333333333333'));assert(!html.includes('mining-contract-row'));assert(!html.includes('reward-daily-dots'));assert(html.includes('node-heading-center'));await ui.click('homeContract');assert(opened.includes('1 of 3'));assert(opened.includes('+0.05 CR'));await ui.click('homeBonuses');assert(opened.includes('Reward for 10 views'));assert(opened.includes('+2.00 CR · +25 Gems'));assert(opened.includes('Views today: 1/75'));assert.equal(calls,0);assert.equal(ads,0);});
test('gold dot only indicates an available reward; claimed rewards and unearned goals remain quiet',()=>{let s=fresh();s=act(s,'daily').state;let v=E.view(s,T);assert.equal(K.create(helpers).bonusAvailable(v),false);assert(H.create(helpers).render(v).includes('node-bonus-dot" hidden'));s=watches(s,10);v=E.view(s,T+650000);assert(K.create(helpers).bonusAvailable(v));s=act(s,'rewardViewBonusClaim',{dayKey:v.rewardMining.day.key,views:10},T+650000).state;assert.equal(K.create(helpers).bonusAvailable(E.view(s,T+650000)),false);});
test('contract completion briefly displays a full ring and check before the next contract',()=>{const ui=H.create(helpers);ui.render(E.view(watches(fresh(),2),T+126000));const html=ui.render(E.view(watches(fresh(),3),T+133000));assert(html.includes('node-contract-ring is-complete'));assert(html.includes('stroke-dasharray="100 100"'));assert(html.includes('✓'));});
test('repeated gift collection taps cannot launch concurrent claims or an ad',async()=>{let calls=0,resolve,opened='',ads=0;const v=E.view(watches(fresh(),10),T+650000),ui=H.create({...helpers,view:()=>v,action:async()=>{calls++;return new Promise(r=>resolve=r);},toast(){},watchRewardAd:async()=>ads++,openSheet:(_,html)=>opened=html});const args={dayKey:v.rewardMining.day.key,views:10},first=ui.click('homeBonusViews',null,args);await ui.click('homeBonusViews',null,args);assert.equal(calls,1);resolve({credited:5});await first;assert(opened.includes('Reward for 10 views'));assert.equal(ads,0);});
