const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Worker}=require('node:worker_threads'),{Readable}=require('node:stream'),{createHmac}=require('node:crypto');
const {Store}=require('../server/store.cjs'),{createHandler}=require('../server/index.cjs'),{verifyTelegram}=require('../server/auth.cjs');
const T=Date.UTC(2026,8,17,12);
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bountera-test-')),file=path.join(dir,'state.sqlite');let store=new Store(file);t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});store.ensureUser('u',{},false,T);return {file,get store(){return store;},reopen(){store.close();store=new Store(file);}};}
test('restart and lost response retry preserve exact result and balances',t=>{const f=fixture(t),a=f.store.act('u','startAd',{},'request-start',T).session;const paid=f.store.act('u','confirmAd',{id:a.id},'request-confirm',T+4000);f.reopen();const retry=f.store.act('u','confirmAd',{id:a.id},'request-confirm',T+6000);assert.deepEqual(retry.confirmation,paid.confirmation);assert.equal(retry.replayed,true);assert.equal(retry.state.balance.cr,10);assert.equal(retry.state.series.views,1);assert.equal(retry.state.ledger.length,1);assert.throws(()=>f.store.act('u','claimDaily',{},'request-confirm',T+6000),/reused/);});
test('duplicate callbacks and new event ID for same session credit once',t=>{const f=fixture(t),a=f.store.act('u','startAd',{},'request-start',T).session,event={eventId:'event-1',userId:'u',kind:'ad',sessionId:a.id};const paid=f.store.providerEvent('provider',event,T+4000);assert.equal(f.store.providerEvent('provider',event,T+5000).replayed,true);assert.deepEqual(f.store.providerEvent('provider',{...event,eventId:'event-2'},T+5000).confirmation,paid.confirmation);assert.equal(f.store.read('u').balance.cr,10);});
test('database uniqueness atomically rolls back base, counter and bonus',t=>{const f=fixture(t);for(let n=0;n<9;n++){const a=f.store.act('u','startAd',{},'start-'+n+'-request',T+n*5000).session;f.store.act('u','confirmAd',{id:a.id},'confirm-'+n+'-request',T+n*5000+4000);}const a=f.store.act('u','startAd',{},'start-tenth',T+50000).session;f.store.db.prepare('INSERT INTO ledger VALUES(?,?,?,?,?,?,?,?,?)').run('u','conflict','milestone',100,'prior',1,10,'completed','{}');assert.throws(()=>f.store.act('u','confirmAd',{id:a.id},'confirm-tenth',T+54000),/UNIQUE/);assert.equal(f.store.read('u').balance.cr,90);assert.equal(f.store.read('u').series.views,9);assert.equal(f.store.read('u').ads.sessions[a.id].status,'started');});
test('four parallel SQLite connections cannot double-pay tenth view',async t=>{const f=fixture(t);for(let n=0;n<9;n++){const a=f.store.act('u','startAd',{},'parallel-start-'+n,T+n*5000).session;f.store.act('u','confirmAd',{id:a.id},'parallel-confirm-'+n,T+n*5000+4000);}const a=f.store.act('u','startAd',{},'parallel-tenth',T+50000).session;
 const source=`const {parentPort,workerData}=require('node:worker_threads');const {Store}=require(workerData.module);const s=new Store(workerData.file);parentPort.postMessage('ready');parentPort.once('message',()=>{try{const r=s.act('u','confirmAd',{id:workerData.id},workerData.key,workerData.now);parentPort.postMessage({balance:r.state.balance.cr});}catch(e){parentPort.postMessage({error:e.message});}finally{s.close();}});`;
 const workers=Array.from({length:4},(_,i)=>new Worker(source,{eval:true,workerData:{module:require.resolve('../server/store.cjs'),file:f.file,id:a.id,key:'parallel-callback-'+i,now:T+54000}}));
 t.after(()=>Promise.all(workers.map(w=>w.terminate())));await Promise.all(workers.map(w=>new Promise((resolve,reject)=>{w.once('message',resolve);w.once('error',reject);})));const results=workers.map(w=>new Promise((resolve,reject)=>{w.once('message',resolve);w.once('error',reject);}));workers.forEach(w=>w.postMessage('go'));for(const r of await Promise.all(results)){assert.equal(r.error,undefined);assert.equal(r.balance,200);}const s=f.store.read('u');assert.equal(s.series.views,10);assert.equal(s.ledger.filter(x=>x.type==='milestone').length,1);assert.equal(s.ledger.filter(x=>x.type==='ad').length,10);
});
function telegramData(token,now=Date.now(),id=1234){const p=new URLSearchParams({auth_date:String(Math.floor(now/1000)),user:JSON.stringify({id,first_name:'Test'})});const check=[...p].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+'='+v).join('\n');const secret=createHmac('sha256','WebAppData').update(token).digest();p.set('hash',createHmac('sha256',secret).update(check).digest('hex'));return p.toString();}
test('Telegram identity, signature and freshness validated',()=>{const data=telegramData('test-token',T);assert.equal(verifyTelegram(data,'test-token',T).id,1234);assert.throws(()=>verifyTelegram(data,'wrong-token',T),/signature/);assert.throws(()=>verifyTelegram(data,'test-token',T+3601000),/expired/);assert.throws(()=>verifyTelegram(data+'&user={}','test-token',T),/Duplicate/);});
async function request(handler,url,method='GET',body,headers={}){const raw=body===undefined?'':typeof body==='string'?body:JSON.stringify(body);const req=Readable.from([raw]);Object.assign(req,{url,method,headers});let status,outHeaders,text='';const res={writeHead(s,h){status=s;outHeaders=h;},end(chunk=''){text+=chunk;}};await handler(req,res);return {status,headers:outHeaders,data:text?JSON.parse(text):null};}
test('production API rejects forged credit commands and validates signed callbacks',async t=>{const f=fixture(t),origin='https://bountera.example',secret='test-provider-secret',handler=createHandler(f.store,{mode:'production',origin,botToken:'test-token',providerName:'test',callbackSecret:secret});const headers={origin,'content-type':'application/json'};
 const login=await request(handler,'/api/login','POST',{initData:telegramData('test-token')},headers);assert.equal(login.status,200);const user=login.data.state.user.id;const auth={...headers,cookie:login.headers['Set-Cookie'].split(';')[0],'x-csrf-token':login.data.csrf,'idempotency-key':'api-request-1'};
 for(const action of ['confirmAd','verifyTask','adminAdjust'])assert.equal((await request(handler,'/api/action','POST',{action,payload:{cr:999999}},auth)).status,403);
 assert.equal((await request(handler,'/api/action','POST',{action:'claimDaily'},{...auth,origin:'https://evil.example'})).status,403);
 const started=await request(handler,'/api/action','POST',{action:'startAd',payload:{rewardCents:9999}},auth);assert.equal(started.status,200);const a=started.data.session;
 f.store.transaction(()=>{const s=f.store.read(user);s.ads.sessions[a.id].readyAt=Date.now()-1;f.store.persist(user,s);});
 const raw=JSON.stringify({eventId:'api-event',userId:user,kind:'ad',sessionId:a.id}),timestamp=String(Date.now());const signed={'x-provider-timestamp':timestamp,'x-provider-signature':createHmac('sha256',secret).update(timestamp+'.'+raw).digest('hex')};
 assert.equal((await request(handler,'/api/provider/callback','POST',raw,{...signed,'x-provider-signature':'bad'})).status,400);assert.equal(f.store.read(user).balance.cr,0);
 const confirmed=await request(handler,'/api/provider/callback','POST',raw,signed);assert.equal(confirmed.status,200);assert.equal(confirmed.data.confirmation.totalCents,10);assert.equal((await request(handler,'/api/provider/callback','POST',raw,signed)).data.replayed,true);
 const again=await request(handler,'/api/login','POST',{initData:telegramData('test-token')},headers);assert.equal(again.data.state.user.id,user);assert.equal(again.data.state.balance.cr,10);assert.equal((await request(handler,'/api/state','GET',undefined,auth)).data.state.series.views,1);
});
test('task callback credits once without ad progress',t=>{const f=fixture(t);f.store.act('u','startTask',{id:'news'},'task-start-request',T);const event={eventId:'task-event',userId:'u',kind:'task',taskId:'news'};f.store.providerEvent('provider',event,T);f.store.providerEvent('provider',{...event,eventId:'another-event'},T);assert.equal(f.store.read('u').balance.cr,5000);assert.equal(f.store.read('u').series.views,0);});
test('server demo withdrawal completion still works',t=>{const f=fixture(t);f.store.ensureUser('demo',{},true,T);f.store.act('demo','connectWallet',{},'wallet-connect',T);const w=f.store.act('demo','withdraw',{amount:100000,requestId:'withdraw-1'},'withdraw-request',T).withdrawal;f.store.act('demo','adminWithdrawal',{id:w.id,status:'approved'},'approve-request',T);f.store.act('demo','adminWithdrawal',{id:w.id,status:'confirmed'},'complete-request',T);assert.equal(f.store.read('demo').balance.reserved,0);});
test('Farm production API authenticates identity, ignores forged terms and reconciles replayed claims',async t=>{
 const f=fixture(t),origin='https://farm.example',handler=createHandler(f.store,{mode:'production',origin,botToken:'farm-test-token'}),headers={origin,'content-type':'application/json'};
 assert.equal((await request(handler,'/api/farm')).status,401);
 async function login(id){const r=await request(handler,'/api/login','POST',{initData:telegramData('farm-test-token',Date.now(),id)},headers);return {user:r.data.state.user.id,headers:{...headers,cookie:r.headers['Set-Cookie'].split(';')[0],'x-csrf-token':r.data.csrf}};}
 const a=await login(111),b=await login(222);
 const started=await request(handler,'/api/action','POST',{action:'farmStart',payload:{userId:b.user,durationMs:1,rewardCents:999999,startedAt:0}},{...a.headers,'idempotency-key':'farm-api-start'});
 assert.equal(started.status,200);assert.equal(started.data.farm.session.userId,a.user);assert.equal(started.data.farm.session.rewardCents,20);assert.equal(started.data.farm.session.durationMs,14400000);
 const early=await request(handler,'/api/action','POST',{action:'farmClaim',payload:{id:started.data.session.id,now:Date.now()+99999999}},{...a.headers,'idempotency-key':'farm-api-early'});assert.equal(early.status,400);assert.match(early.data.error,/not ready/);
 // A backdated server fixture advances the session without waiting four hours.
 const ready=f.store.act(b.user,'farmStart',{},'farm-api-backdated',Date.now()-14400001).session;
 const stolen=await request(handler,'/api/action','POST',{action:'farmClaim',payload:{id:ready.id,userId:b.user}},{...a.headers,'idempotency-key':'farm-api-stolen'});assert.equal(stolen.status,400);
 assert.equal((await request(handler,'/api/farm','GET',undefined,b.headers)).data.farm.status,'ready');
 const auth={...b.headers,'idempotency-key':'farm-api-claim'},body={action:'farmClaim',payload:{id:ready.id,rewardCents:999999}};
 const paid=await request(handler,'/api/action','POST',body,auth),retry=await request(handler,'/api/action','POST',body,auth);
 assert.equal(paid.status,200);assert.equal(paid.data.state.balance.cr,20);assert.equal(retry.data.replayed,true);assert.equal(retry.data.state.balance.cr,20);assert.equal(retry.data.farm.stats.completedSessions,1);assert.equal(retry.data.farm.status,'idle');assert.equal(f.store.read(a.user).balance.cr,0);
});
