const {test}=require('node:test'),assert=require('node:assert/strict'),V=require('../assets/telegram-viewport.js');
function setup(tg){const props={},events={},winEvents={},docEvents={},classes={},rootClasses={},calls={ready:0,expand:0,on:0,off:0};
 const w={Telegram:tg?{WebApp:tg}:undefined,innerHeight:844,innerWidth:390,location:{hash:'',search:''},navigator:{hardwareConcurrency:4},visualViewport:{height:844,offsetTop:0,addEventListener(){},removeEventListener(){}},addEventListener:(n,f)=>winEvents[n]=f,removeEventListener(){},getComputedStyle:()=>({getPropertyValue:()=>''}),setTimeout:f=>f()};
 const d={documentElement:{style:{setProperty:(k,v)=>props[k]=v},classList:{toggle:(k,v)=>rootClasses[k]=v,add:k=>rootClasses[k]=true,remove:k=>rootClasses[k]=false,contains:k=>!!rootClasses[k]}},body:{classList:{toggle:(k,v)=>classes[k]=v}},addEventListener:(n,f)=>docEvents[n]=f,removeEventListener(){},querySelector:()=>null};
 const bind=t=>{t.ready=()=>calls.ready++;t.expand=()=>calls.expand++;t.onEvent=(n,f)=>{calls.on++;events[n]=f;};t.offEvent=()=>calls.off++;};if(tg)bind(tg);
 const v=V.create({window:w,document:d});return {v,w,d,props,events,winEvents,docEvents,classes,calls,bind};
}
const host=()=>({safeAreaInset:{top:47,bottom:34,left:0,right:0},contentSafeAreaInset:{top:56,bottom:0,left:0,right:0},isFullscreen:true,viewportHeight:844,viewportStableHeight:844});
test('all four system and content insets refresh with one set of Telegram subscriptions',()=>{const tg=host(),f=setup(tg);assert.equal(f.props['--app-system-top'],'47px');assert.equal(f.props['--app-system-bottom'],'34px');assert.equal(f.props['--app-chrome-top'],'56px');assert(f.classes['telegram-chrome']);assert(f.classes['low-effects']);assert.equal(f.calls.on,5);assert.equal(f.calls.ready,1);assert.equal(f.calls.expand,1);tg.safeAreaInset={top:0,bottom:20,left:4,right:6};tg.contentSafeAreaInset={top:32,bottom:8,left:2,right:3};f.events.contentSafeAreaChanged();assert.equal(f.props['--app-chrome-top'],'32px');assert.equal(f.props['--app-system-top'],'0px');assert.equal(f.props['--app-system-left'],'4px');assert.equal(f.props['--app-chrome-right'],'3px');assert.equal(f.calls.on,5);});
test('transient height updates clip the frame without moving stable navigation or shrinking scene coordinates',()=>{const tg=host(),f=setup(tg);tg.viewportHeight=650;tg.viewportStableHeight=650;f.events.viewportChanged({isStateStable:false});assert.equal(f.props['--app-viewport-height'],'650px');assert.equal(f.props['--app-stable-height'],'844px');assert.equal(f.props['--app-scene-height'],'844px');assert.equal(f.props['--app-nav-viewport-height'],'844px');f.events.viewportChanged({isStateStable:true});assert.equal(f.props['--app-stable-height'],'650px');assert.equal(f.props['--app-nav-viewport-height'],'650px');assert.equal(f.props['--app-scene-height'],'844px');tg.viewportStableHeight=tg.viewportHeight=844;f.events.viewportChanged({isStateStable:true});assert.equal(f.props['--app-stable-height'],'844px');});
test('viewport size can rebase on rotation, but inset changes preserve the scene size',()=>{const tg=host(),f=setup(tg);tg.safeAreaInset.top=59;f.events.safeAreaChanged();assert.equal(f.props['--app-scene-height'],'844px');f.w.innerWidth=844;f.w.innerHeight=390;tg.viewportStableHeight=tg.viewportHeight=390;f.winEvents.resize();assert.equal(f.props['--app-scene-height'],'390px');});
test('late SDK initialization, reactivation and teardown do not duplicate handlers',()=>{const f=setup();assert.equal(f.v.state,null);const tg=host();f.bind(tg);f.w.Telegram={WebApp:tg};f.winEvents.load();f.winEvents.load();assert.equal(f.calls.on,5);assert.equal(f.calls.expand,1);tg.safeAreaInset.bottom=20;f.events.activated();assert.equal(f.v.state.safe.bottom,20);f.v.destroy();assert.equal(f.calls.off,5);tg.safeAreaInset.bottom=10;f.v.update();assert.equal(f.v.state.safe.bottom,20);});
test('missing dimensions and invalid insets use browser geometry without NaN or negative padding',()=>{const f=setup({isFullscreen:true,safeAreaInset:{top:-5,bottom:NaN},viewportHeight:Infinity});assert.equal(f.props['--app-system-top'],'0px');assert.equal(f.props['--app-system-bottom'],'0px');assert.equal(f.props['--app-chrome-top'],'56px');assert.equal(f.props['--app-stable-height'],'844px');assert(Object.values(f.props).every(x=>!x.includes('NaN')&&!x.includes('Infinity')));});
test('keyboard constrains the frame and navigation without reflowing the scene',()=>{const f=setup(host());f.d.activeElement={matches:()=>true};f.w.visualViewport.height=480;f.w.visualViewport.offsetTop=10;f.winEvents.resize();assert(f.v.state.keyboard);assert.equal(f.props['--app-nav-viewport-height'],'480px');assert.equal(f.props['--app-viewport-height'],'480px');assert.equal(f.props['--app-viewport-top'],'10px');assert.equal(f.props['--app-scene-height'],'844px');f.d.activeElement=null;f.w.visualViewport.height=844;f.winEvents.resize();assert.equal(f.props['--app-nav-viewport-height'],'844px');});
