'use strict';const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{Store}=require('./store.cjs'),{verifyTelegram}=require('./auth.cjs'),E=require('../assets/engine.js');
function handler(store,{origin='http://127.0.0.1:4173',mode='demo',botToken}={}){const root=path.resolve(__dirname,'..'),reply=(res,status,data,headers={})=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store',...headers});res.end(JSON.stringify(data));};return async(req,res)=>{try{const url=new URL(req.url,origin),cookie=Object.fromEntries(String(req.headers.cookie||'').split(';').map(s=>s.trim().split('='))),session=store.session(cookie.bountera_session);if(url.pathname.startsWith('/api/')){const body=async()=>{let raw='';for await(const part of req){raw+=part;if(raw.length>16384)throw Error('Request too large');}return JSON.parse(raw||'{}');};
 if(req.method==='POST'&&(req.headers.origin!==origin||!String(req.headers['content-type']).startsWith('application/json')))return reply(res,403,{error:'Invalid request origin'});
 if(url.pathname==='/api/mining/bootstrap'&&req.method==='GET'){const state=session?store.ensure(session.user_id):null;return reply(res,200,{api:'bountera-mining-v5',mode,authenticated:!!session,state,csrf:session?.csrf,serverTime:Date.now()});}
 if(url.pathname==='/api/mining/login'&&req.method==='POST'){const data=await body();let id,profile;if(mode==='demo'){id='demo-'+randomUUID();profile={name:'Explorer'};}else{const user=verifyTelegram(data.initData,botToken);id='telegram-'+user.id;profile={name:user.first_name,username:user.username||'explorer'};}const state=store.ensure(id,profile),login=store.login(id);return reply(res,200,{state,csrf:login.csrf,mode,serverTime:Date.now()},{'Set-Cookie':`bountera_session=${login.token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${origin.startsWith('https:')?'; Secure':''}`});}
 if(!session)return reply(res,401,{error:'Sign in again / Войдите снова'});
 if(url.pathname==='/api/mining/state'&&req.method==='GET')return reply(res,200,{state:E.view(store.read(session.user_id)).state,serverTime:Date.now()});
 if(url.pathname==='/api/mining/action'&&req.method==='POST'){if(req.headers['x-csrf-token']!==session.csrf)return reply(res,403,{error:'Invalid request token'});if(mode!=='demo')return reply(res,503,{error:'This game build is demo-only. Production integrations are not enabled.'});const data=await body(),out=store.act(session.user_id,data.action,data.payload||{},req.headers['idempotency-key']);return reply(res,200,{...out,serverTime:Date.now()});}
 return reply(res,404,{error:'Endpoint not found'});}
 if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end();}const relative=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));if(relative!=='index.html'&&!/^assets\/[\w.-]+\.(js|css|png|svg|webp)$/.test(relative)){res.writeHead(404);return res.end();}const file=path.join(root,relative);if(!fs.existsSync(file)){res.writeHead(404);return res.end();}res.writeHead(200,{'Content-Type':{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp'}[path.extname(file)],'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')return res.end();fs.createReadStream(file).pipe(res);
}catch(e){reply(res,400,{error:e.message});}};}
if(require.main===module){const port=Number(process.env.PORT||4173),origin=process.env.PUBLIC_ORIGIN||`http://127.0.0.1:${port}`,file=process.env.DATABASE_PATH||path.join(__dirname,'../.data/bountera.sqlite'),mode=process.env.BOUNTERA_MODE||'demo';if(mode!=='demo')throw Error('This release is a demo. Configure real integrations before enabling production.');fs.mkdirSync(path.dirname(file),{recursive:true});const store=new Store(file),server=http.createServer(handler(store,{origin,mode}));server.listen(port,'127.0.0.1',()=>console.log('Bountera mining demo: '+origin));process.once('SIGINT',()=>server.close(()=>{store.close();process.exit();}));}module.exports={handler};
