'use strict';const {DatabaseSync}=require('node:sqlite'),{createHash,randomBytes}=require('node:crypto'),E=require('../assets/engine.js'),C=require('../assets/config.js');const hash=x=>createHash('sha256').update(x).digest('hex');
class Store{
 constructor(file,config=C){this.config=config;this.db=new DatabaseSync(file);this.db.exec(`PRAGMA journal_mode=WAL;PRAGMA busy_timeout=10000;CREATE TABLE IF NOT EXISTS mining_accounts(user_id TEXT PRIMARY KEY,state TEXT NOT NULL);CREATE TABLE IF NOT EXISTS mining_ledger(user_id TEXT NOT NULL,id TEXT NOT NULL,type TEXT NOT NULL,source TEXT NOT NULL,record TEXT NOT NULL,PRIMARY KEY(user_id,id),UNIQUE(user_id,type,source));CREATE TABLE IF NOT EXISTS mining_requests(user_id TEXT NOT NULL,id TEXT NOT NULL,fingerprint TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(user_id,id));CREATE TABLE IF NOT EXISTS login_sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,csrf TEXT NOT NULL,expires_at INTEGER NOT NULL);`);}
 tx(fn){this.db.exec('BEGIN IMMEDIATE');try{const out=fn();this.db.exec('COMMIT');return out;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 ensure(id,profile={},now=Date.now()){return this.tx(()=>{const found=this.db.prepare('SELECT state FROM mining_accounts WHERE user_id=?').get(id);if(found)return JSON.parse(found.state);let legacy=null;if(this.db.prepare("SELECT 1 FROM sqlite_master WHERE name='accounts'").get()){const old=this.db.prepare('SELECT state FROM accounts WHERE user_id=?').get(id);if(old)legacy=JSON.parse(old.state);}const s=E.initial(this.config,now,legacy);s.user={...s.user,...profile,id};E.settle(s,now);this.persist(id,s);return s;});}
 read(id){const row=this.db.prepare('SELECT state FROM mining_accounts WHERE user_id=?').get(id);if(!row)throw Error('Account not found');return JSON.parse(row.state);}
 persist(id,s){this.db.prepare('INSERT INTO mining_accounts VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET state=excluded.state').run(id,JSON.stringify(s));const q=this.db.prepare('INSERT INTO mining_ledger VALUES(?,?,?,?,?) ON CONFLICT(user_id,id) DO NOTHING');for(const x of s.ledger)q.run(id,x.id,x.type,x.source,JSON.stringify(x));}
 act(id,action,payload,key,now=Date.now()){if(typeof key!=='string'||key.length<8||key.length>200)throw Error('Invalid request ID');return this.tx(()=>{const fingerprint=hash(JSON.stringify({action,payload})),old=this.db.prepare('SELECT * FROM mining_requests WHERE user_id=? AND id=?').get(id,key);if(old){if(old.fingerprint!==fingerprint)throw Error('Request ID conflict');return {...JSON.parse(old.result),state:this.read(id),replayed:true};}const out=E.apply(this.read(id),action,payload,now,key);this.persist(id,out.state);const {state,...result}=out;this.db.prepare('INSERT INTO mining_requests VALUES(?,?,?,?)').run(id,key,fingerprint,JSON.stringify(result));return out;});}
 login(id,now=Date.now()){const token=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');this.db.prepare('INSERT INTO login_sessions VALUES(?,?,?,?)').run(hash(token),id,csrf,now+30*86400000);return {token,csrf};}
 session(token,now=Date.now()){return token?this.db.prepare('SELECT user_id,csrf FROM login_sessions WHERE token_hash=? AND expires_at>?').get(hash(token),now):null;}
 close(){this.db.close();}
}module.exports={Store};
