const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../assets/engine.js'),C=require('../assets/config.js'),J=require('../assets/home-system.js'),N=require('../assets/node-system.js'),{Store}=require('../server/store.cjs');
const T=Date.UTC(2026,8,26,12),H=3600000;let seq=0;
const fresh=()=>E.initial(C,T),act=(s,a,p={},t=T,key='home-test-'+(++seq))=>E.apply(s,a,p,t,key).state;
const state=(s,t)=>E.view(s,t).state,scene=(s,t)=>E.view(s,t).home;
function ad(s,p,t){const o=E.apply(s,'adStart',p,t,'home-ad-'+(++seq));return act(o.state,'adConfirm',{id:o.ad.id},t+C.ads.durationMs);}
test('accelerating travel or deployment preserves the event reward duration',()=>{let s=fresh();s.is_first_session=false;s.nodes.gpu=1;s=act(s,'nodeUpgrade',{id:'radar',currency:'cr'});const galaxy=s.nodeHub.event.galaxy;s=act(s,'homeLaunch',{galaxy});let e=s.nodeHub.expeditions[galaxy];assert.equal(e.eventUntil-e.activeAt,H);s=ad(s,{purpose:'travel',galaxy},T);e=s.nodeHub.expeditions[galaxy];assert.equal(e.eventUntil-e.activeAt,H);s=ad(s,{purpose:'deploy',galaxy},e.arrivesAt);e=s.nodeHub.expeditions[galaxy];assert.equal(e.eventUntil-e.activeAt,H);});
test('first expedition preserves Carrier, Station and swarm release as distinct timed stages',()=>{let s=fresh();assert.equal(scene(s,T).phase,'ready');s=act(s,'homeLaunch');const e=s.nodeHub.expeditions.aurora;assert.equal(e.arrivesAt,T+15000);assert.equal(e.swarmAt,T+30000);assert.equal(e.activeAt,T+45000);assert.equal(scene(s,T+14999).phase,'travel');assert.equal(scene(s,T+15000).phase,'deploying');assert.equal(scene(s,T+29999).releasing,false);assert.equal(scene(s,T+30000).releasing,true);assert.equal(scene(s,T+45000).phase,'active');assert.equal(state(s,T+45000).nodeHub.expeditions.aurora.micro,0);assert.equal(s.is_first_session,false);});
test('first claim is available within a minute, exchanges only its buffer and grants one welcome boost',()=>{let s=act(fresh(),'homeLaunch'),before=s.balance.cr,reserve=s.mine.micro;assert.throws(()=>act(s,'homeCollect',{galaxy:'aurora'},T+45000));const at=T+60000,o=E.apply(s,'homeCollect',{galaxy:'aurora'},at,'first-home-claim');s=o.state;assert.equal(o.credited,2);assert.equal(s.balance.cr,before+2);assert(s.mine.micro>=reserve&&s.mine.micro<reserve+20000);assert.equal(s.homeJourney.completedAt,at);assert.equal(s.nodeHub.expeditions.aurora.welcomeBoostUntil,at+1800000);const retry=E.apply(s,'homeCollect',{galaxy:'aurora'},at,'first-home-claim');assert.equal(retry.state.balance.cr,s.balance.cr);s=act(s,'homeCollect',{galaxy:'aurora'},T+90000);assert.equal(s.ledger.filter(x=>x.type==='welcome_boost').length,1);});
test('second expedition uses normal timers even before finishing onboarding, with independent selection',()=>{let s=fresh();s.nodes.relay=2;s=act(s,'homeLaunch');s=act(s,'homeSelect',{galaxy:'cygnus'},T+1000);assert.equal(scene(s,T+1000).phase,'ready');s=act(s,'homeLaunch',{},T+1000);const e=s.nodeHub.expeditions.cygnus;assert.equal(e.arrivesAt,T+1000+H);assert.equal(e.activeAt,e.arrivesAt+315000);assert.equal(e.tutorial,false);s=act(s,'homeSelect',{galaxy:'aurora'},T+60000);assert.equal(scene(s,T+60000).phase,'active');assert.equal(s.nodeHub.expeditions.cygnus.micro,0);});
test('onboarding flags, timers and accumulated resources survive reload and offline catch-up',()=>{let s=act(fresh(),'homeLaunch');const restored=E.load(JSON.parse(JSON.stringify(s))),end=T+5*60000,once=state(restored,end);for(let t=T;t<end;t+=777)E.settle(s,t);E.settle(s,end);assert.equal(s.nodeHub.expeditions.aurora.micro,once.nodeHub.expeditions.aurora.micro);assert.equal(s.homeJourney.startedAt,T);assert.equal(s.is_first_session,false);const amount=s.nodeHub.expeditions.aurora.micro;E.settle(s,T-1000);assert.equal(s.nodeHub.expeditions.aurora.micro,amount);});
test('legacy accounts are not reset or forced through tutorial and retain in-flight deadlines',()=>{let s=fresh();delete s.is_first_session;E.settle(s,T);s=act(s,'nodeDeploy',{id:'relay',galaxy:'aurora'});const e=s.nodeHub.expeditions.aurora,deadline=e.activeAt;delete s.homeJourney;delete e.journeyInitialized;const restored=state(E.load(s),T+1000);assert.equal(restored.nodeHub.expeditions.aurora.activeAt,deadline);assert.equal(scene(restored,T+1000).minimal,false);assert.equal(restored.balance.cr,s.balance.cr);});
test('instant launch reward skips only flight; cancelled ads do not launch anything',()=>{let s=fresh(),o=E.apply(s,'adStart',{purpose:'launch',galaxy:'aurora'},T,'launch-ad');s=act(o.state,'adCancel',{id:o.ad.id},T+1000);assert.equal(Object.keys(s.nodeHub.expeditions).length,0);s=ad(s,{purpose:'launch',galaxy:'aurora'},T+240000);const e=s.nodeHub.expeditions.aurora;assert.equal(e.arrivesAt,T+243000);assert.equal(e.activeAt,e.arrivesAt+30000);assert.equal(scene(s,e.arrivesAt).phase,'deploying');});
test('x4 ad is expedition-bound, expires exactly and does not stack with x2',()=>{let s=fresh();s.is_first_session=false;s=act(s,'homeLaunch');const at=s.nodeHub.expeditions.aurora.activeAt;s=ad(s,{purpose:'boost4',galaxy:'aurora'},at);const e=s.nodeHub.expeditions.aurora;e.overclockUntil=at+24*H;assert.equal(N.metrics(s,e,at+3000).rate,4000000);assert.equal(N.metrics(s,e,e.boost4Until).rate,2000000);assert.throws(()=>act(s,'adStart',{purpose:'boost4',galaxy:'aurora'},at+240000));});
test('first-reward doubling adds only first claim amount and cannot be repeated',()=>{let s=act(fresh(),'homeLaunch');s=act(s,'homeCollect',{galaxy:'aurora'},T+60000);const before=s.balance.cr;s=ad(s,{purpose:'firstReward'},T+61000);assert.equal(s.balance.cr,before+s.homeJourney.firstReward);assert.equal(s.homeJourney.firstRewardDoubled,true);assert.throws(()=>act(s,'adStart',{purpose:'firstReward'},T+301000));});
test('Home controls unlock together at Swarm mining and stay open in other galaxies',()=>{let s=act(fresh(),'homeLaunch');assert.equal(scene(s,T+44999).minimal,true);assert.equal(scene(s,T+44999).partial,true);assert.equal(scene(s,T+45000).minimal,false);assert.equal(scene(s,T+45000).partial,false);s=act(s,'homeSelect',{galaxy:'cygnus'},T+45000);assert.equal(scene(s,T+45000).phase,'ready');assert.equal(scene(s,T+45000).minimal,false);s=act(s,'nodeRecall',{galaxy:'aurora'},T+45000);assert.equal(scene(E.load(s),T+46000).partial,false);assert(scene(s,T+60000).dots>=8);s.nodes.genesis=1;assert.equal(scene(s,T+60000).tier.id,'genesis');assert(scene(s,T+60000).dots<=15);});
test('database replay after lost first-claim response credits once and preserves first-session flag',()=>{const store=new Store(':memory:');try{store.ensure('home-user',{},T);store.act('home-user','homeLaunch',{},'home-launch-0001',T);assert.throws(()=>store.act('home-user','homeLaunch',{},'home-launch-0002',T));const first=store.act('home-user','homeCollect',{galaxy:'aurora'},'home-claim-00001',T+60000),retry=store.act('home-user','homeCollect',{galaxy:'aurora'},'home-claim-00001',T+60000);assert.equal(first.state.balance.cr,retry.state.balance.cr);assert.equal(retry.state.is_first_session,false);assert.equal(store.db.prepare("SELECT COUNT(*) n FROM mining_ledger WHERE type='welcome_boost'").get().n,1);}finally{store.close();}});

